/**
 * lib/copilot/memory/memory-repository.ts
 *
 * Agentik — Copilot Memory Engine — Repository Contract
 * Sprint: AGENTIK-COPILOT-MEMORY-ENGINE-01
 *
 * Pure interface contract for memory persistence.
 * No Prisma. No implementation. Just the contract.
 *
 * Current implementation: InMemoryMemoryRepository (in-memory-memory-repository.ts)
 * Future implementation:  PrismaMemoryRepository  (AGENTIK-COPILOT-MEMORY-PERSIST-01)
 */

import type {
  MemoryEntry,
  CreateMemoryInput,
  UpdateMemoryInput,
  MemorySearchOptions,
} from "./memory-types";

// ── Repository interface ───────────────────────────────────────────────────────

/**
 * MemoryRepository — persistence contract for Copilot strategic memory.
 *
 * All methods are async to support both in-memory and DB implementations.
 * All methods NEVER throw — return null/false/empty on failure.
 */
export interface MemoryRepository {
  /**
   * Persist a new memory entry.
   * ID and timestamps are generated by the implementation.
   */
  saveMemory(input: CreateMemoryInput): Promise<MemoryEntry>;

  /**
   * Update an existing memory entry by ID.
   * Returns the updated entry, or null if not found.
   */
  updateMemory(id: string, updates: UpdateMemoryInput): Promise<MemoryEntry | null>;

  /**
   * Delete a memory entry by ID.
   * Returns true if deleted, false if not found.
   */
  deleteMemory(id: string): Promise<boolean>;

  /**
   * Retrieve a single memory entry by ID.
   * Returns null if not found.
   * Does NOT cross org boundaries.
   */
  getMemory(id: string): Promise<MemoryEntry | null>;

  /**
   * Search memory entries for a tenant.
   * All filters in options are ANDed.
   * Results are ordered by importance DESC, then createdAt DESC.
   */
  searchMemory(orgSlug: string, options: MemorySearchOptions): Promise<MemoryEntry[]>;

  /**
   * List all memory entries for a tenant, ordered by importance DESC, createdAt DESC.
   * Use limit in options to cap results.
   */
  listMemories(orgSlug: string, options?: Pick<MemorySearchOptions, "limit">): Promise<MemoryEntry[]>;

  /**
   * Return the count of memories for a tenant.
   */
  countMemories(orgSlug: string): Promise<number>;

  /**
   * Clear all memories for a tenant. Use only in tests.
   */
  clearMemories(orgSlug: string): Promise<void>;
}
