/**
 * lib/marketing-studio/commerce/shopify-statistics-types.ts
 *
 * SHOPIFY-STATISTICS-01 — Canonical domain types for the Statistics module.
 *
 * Platform-agnostic. No Shopify REST field names exposed.
 * All types are usable from service functions, Copilot agents, and
 * automation workers without any React dependency.
 *
 * ── Module structure (SHOPIFY-DECISION-01) ────────────────────────────────────
 *
 *   Shopify
 *   ├── Estadísticas     ← this module
 *   ├── Catálogo
 *   ├── Promociones y descuentos
 *   ├── Banners y landings
 *   ├── Operaciones
 *   └── Configuración
 *
 * ── Copilot query scenarios ───────────────────────────────────────────────────
 *
 *   "¿Qué categoría creció más esta semana?"
 *     → getTrendAnalysis → topSelling comparison by category
 *
 *   "¿Qué promoción tuvo mejor desempeño?"
 *     → getPromotionMetrics → sort by totalCodeUsage
 *
 *   "¿Qué productos necesitan reposición?"
 *     → getCatalogMetrics → outOfStock + lowStock
 *
 *   "¿Qué porcentaje de pedidos terminó en devolución?"
 *     → getSalesMetrics → returnsTotal / orders
 *
 *   "¿Cuál fue el ticket promedio del mes?"
 *     → getSalesMetrics(period="month") → averageOrderValue
 *
 *   "¿Qué está empeorando respecto a la semana pasada?"
 *     → getTrendAnalysis → filter direction="down", sort pct ascending
 *
 * ── Non-AI guarantee ─────────────────────────────────────────────────────────
 *
 *   All values are computed deterministically from real order, catalog and
 *   operational data. ExecutiveInsight is produced by threshold rules only —
 *   never generated by a language model.
 */

// ── Analysis periods ──────────────────────────────────────────────────────────

/**
 * Statistical analysis period.
 * All period-aware functions default to "week" unless specified.
 *
 * Comparison window (for TrendAnalysis):
 *   today      → vs yesterday
 *   yesterday  → vs the day before
 *   week       → last 7 days vs 8–14 days ago
 *   last_week  → 8–14 days ago vs 15–21 days ago
 *   month      → last 30 days vs 31–60 days ago
 *   last_month → 31–60 days ago vs 61–90 days ago
 *   custom     → explicit fromDate/toDate (no comparison period)
 */
export type StatisticsPeriod =
  | "today"
  | "yesterday"
  | "week"
  | "last_week"
  | "month"
  | "last_month"
  | "custom";

// ── Trend direction ───────────────────────────────────────────────────────────

/**
 * Direction of change between current and previous period.
 * Computed from delta: up if delta > 0, down if delta < 0, stable if delta = 0.
 */
export type TrendDirection = "up" | "down" | "stable";

// ── Metric health ─────────────────────────────────────────────────────────────

/**
 * Deterministic health classification for a single KPI.
 *
 *   good     — metric is trending positively or at healthy levels
 *   warning  — metric shows a concerning trend that requires attention
 *   critical — metric has crossed a critical threshold requiring immediate action
 *   neutral  — metric is stable, absent, or data is insufficient to classify
 *
 * NON-AI GUARANTEE: Never set by a language model.
 * All values are derived from fixed threshold rules against real metric data.
 *
 * Copilot routing by health:
 *   critical → surface as P1 in the right rail attention strip
 *   warning  → surface as P2 in the right rail
 *   good     → available for "¿qué mejoró?" queries
 *   neutral  → excluded from attention queries
 */
export type MetricHealth = "good" | "warning" | "critical" | "neutral";

// ── Insight taxonomy ──────────────────────────────────────────────────────────

export type InsightSeverity = "info" | "warning" | "critical";
export type InsightImpact   = "low"  | "medium"  | "high";

/**
 * Priority rank 1–5 where 1 = highest urgency.
 * Controls display order in the executive workspace and Copilot rail.
 */
export type InsightPriority = 1 | 2 | 3 | 4 | 5;

/**
 * Domain category for an executive insight.
 * Feeds Copilot routing — ensures the right agent handles each insight type.
 *
 *   sales       → Diego (finance/commercial)
 *   catalog     → Luca (marketing studio)
 *   promotions  → Luca (marketing studio)
 *   operations  → Diego or Mila
 *   funnel      → Luca (marketing/ads)
 */
export type InsightCategory =
  | "sales"
  | "catalog"
  | "promotions"
  | "operations"
  | "funnel";

// ── Core metric primitives ────────────────────────────────────────────────────

/**
 * A single numeric metric with period-over-period comparison.
 * All values are pre-computed — no client-side calculation required.
 *
 * Copilot read-aloud:
 *   "El valor actual es {current}.
 *    {direction === 'up' ? 'Subió' : direction === 'down' ? 'Bajó' : 'Se mantuvo'}
 *    un {Math.abs(pct).toFixed(1)}%."
 */
export interface TrendMetric {
  /** Value in the current analysis period. */
  current:   number;
  /** Value in the previous period (same duration). */
  previous:  number;
  /** Absolute difference: current − previous. Can be negative. */
  delta:     number;
  /**
   * Percentage change relative to previous: (delta / previous) × 100.
   * Returns 0 when previous = 0 (avoids division by zero).
   * Rounded to 1 decimal place.
   */
  pct:       number;
  direction: TrendDirection;
}

/**
 * A labeled comparison metric for display in tables, cards, and Copilot responses.
 * Extends TrendMetric with display metadata and optional health classification.
 */
export interface ComparisonMetric {
  label:     string;
  current:   number;
  previous:  number;
  delta:     number;
  pct:       number;
  direction: TrendDirection;
  /** Unit label for display: "COP", "%", "unidades", "pedidos". */
  unit?:     string;
  /** Number format hint for UI renderers. */
  format?:   "currency" | "percent" | "number" | "integer";
  /**
   * Deterministic health classification (SHOPIFY-STATISTICS-01B).
   * Present when the metric has both current and previous values.
   */
  metricHealth?: MetricHealth;
  /**
   * Plain-Spanish reason for the health classification.
   * Suitable for Copilot read-aloud without transformation.
   */
  healthReason?: string;
}

// ── Healthed metric ───────────────────────────────────────────────────────────

/**
 * A KPI with full trend context and deterministic health classification.
 *
 * Primary shape for Copilot health queries:
 *   "¿Qué indicadores requieren atención?"     → metricHealth="warning"|"critical"
 *   "¿Qué mejoró esta semana?"                 → metricHealth="good", direction="up"
 *   "¿Qué está empeorando?"                    → direction="down", metricHealth≠"good"
 *   "¿Dónde debo actuar primero?"              → needsAttention[0] in MetricHealthSummary
 *   "Dame un semáforo de la tienda."           → all 7 HealthedMetrics in MetricHealthSummary
 *
 * All values are pre-computed — no client-side calculation required.
 * healthReason is plain Spanish, suitable for Copilot read-aloud as-is.
 *
 * NON-AI GUARANTEE: metricHealth is set by deterministic threshold rules only.
 *
 * Copilot read-aloud template:
 *   "{label}: {healthReason}
 *    Variación: {direction === 'up' ? '↑' : direction === 'down' ? '↓' : '→'}
 *    {Math.abs(deltaPercent).toFixed(1)}% frente al período anterior."
 */
export interface HealthedMetric {
  /** Display label in Spanish. */
  label:         string;
  /** Value in the current analysis period. */
  value:         number;
  /** Value in the previous period (same duration). */
  previousValue: number;
  /** Absolute difference: value − previousValue. */
  delta:         number;
  /**
   * Percentage change: (delta / previousValue) × 100.
   * 0 when previousValue = 0. Rounded to 1 decimal place.
   */
  deltaPercent:  number;
  direction:     TrendDirection;
  metricHealth:  MetricHealth;
  /**
   * Human-readable explanation for the health classification.
   * Generated from metric values only — never from a language model.
   * Example: "Las ventas bajaron 12% frente a la semana anterior."
   */
  healthReason:  string;
}

// ── Sales metrics ─────────────────────────────────────────────────────────────

/**
 * Core commercial performance metrics for a given period.
 * Primary source: Shopify Orders REST API.
 *
 * Data contract:
 *   - Cancelled orders excluded from totalRevenue.
 *   - Voided orders (financial_status="voided") excluded.
 *   - refundsTotal = sum of completed refund transactions.
 *   - netRevenue = totalRevenue − refundsTotal.
 *
 * Copilot: "statistics.getSalesMetrics()"
 */
export interface SalesMetrics {
  /** Gross revenue: sum of total_price for non-cancelled, non-voided orders. */
  totalRevenue:       number;
  /** Total non-cancelled orders in the period. */
  orders:             number;
  /** Average order value: totalRevenue / orders. 0 if no orders. */
  averageOrderValue:  number;
  /** Total line item units sold across all orders. */
  unitsSold:          number;
  /**
   * Unique customer IDs in this order set.
   * Approximation — full accuracy requires full purchase history (SHOPIFY-STATISTICS-05).
   */
  newCustomers:       number;
  /** Customer IDs with more than one order in this set. */
  returningCustomers: number;
  /** Net revenue after refunds: totalRevenue − refundsTotal. Floored at 0. */
  netRevenue:         number;
  /** Total successfully processed refund amounts. */
  refundsTotal:       number;
  /** Orders with at least one returned line item. */
  returnsTotal:       number;
  currency:           string;
  period:             StatisticsPeriod;
  fromDate:           string;   // ISO8601
  toDate:             string;   // ISO8601
}

// ── Funnel metrics ────────────────────────────────────────────────────────────

/**
 * Commercial conversion funnel.
 *
 * Top-of-funnel (visits → cart) requires Shopify Analytics or GA4.
 * Fields are null until connector is wired (SHOPIFY-STATISTICS-03).
 * Bottom-of-funnel (completed orders) always available from REST orders.
 *
 * TODO(SHOPIFY-STATISTICS-03): Connect Google Analytics 4 or Shopify Analytics
 *   for full funnel visibility (visits, product views, add-to-cart, checkout).
 */
export interface FunnelMetrics {
  visits:            number | null;   // null until analytics connector
  productViews:      number | null;
  addToCart:         number | null;
  checkoutStarted:   number | null;
  completed:         number;          // always available
  visitsToCartRate:  number | null;   // null if visits unavailable
  cartToOrderRate:   number | null;
  overallConversion: number | null;
}

// ── Catalog metrics ───────────────────────────────────────────────────────────

/**
 * Product catalog health and performance statistics.
 * Combines Agentik catalog publication state with Shopify order line item data.
 *
 * Copilot: "statistics.getCatalogMetrics()"
 */
export interface CatalogMetrics {
  totalProducts: number;
  /** Products with publicationStatus="published" on the Shopify channel. */
  published:     number;
  /** Products in Agentik catalog but not yet published to Shopify. */
  pending:       number;
  /**
   * Products with zero inventory across all variants.
   * TODO(SHOPIFY-STATISTICS-02): Requires Shopify Inventory API.
   */
  outOfStock:    number;
  /**
   * Products below low-stock threshold (default: 5 units).
   * TODO(SHOPIFY-STATISTICS-02): Requires Shopify Inventory API.
   */
  lowStock:      number;
  /** Published products with no sales in the current period. */
  neverSold:     number;
  /** Top 10 products by revenue, descending. */
  topSelling:    CatalogProductStat[];
  /** Bottom 5 products (with ≥1 sale) by revenue, ascending. */
  bottomSelling: CatalogProductStat[];
}

/**
 * Per-product performance stat derived from order line items.
 */
export interface CatalogProductStat {
  /** Composite ID: "shopify:product:{shopify_product_id}" */
  productId:  string;
  title:      string;
  unitsSold:  number;
  revenue:    number;
  currency:   string;
}

// ── Promotion metrics ─────────────────────────────────────────────────────────

/**
 * Statistics about promotional campaigns.
 * Consumes the Promotions domain — no Shopify price rule internals.
 *
 * Copilot: "statistics.getPromotionMetrics()"
 */
export interface PromotionMetrics {
  active:            number;
  scheduled:         number;
  expired:           number;
  disabled:          number;
  /** Sum of usage_count across all codes for active promotions. */
  totalCodeUsage:    number;
  /**
   * Total discount amount applied across orders.
   * TODO(SHOPIFY-STATISTICS-04): Requires order.discount_applications.
   */
  discountsApplied:  number;
  /**
   * Estimated revenue volume affected by active promotions.
   * TODO(SHOPIFY-STATISTICS-04): Requires order-level discount correlation.
   */
  estimatedImpact:   number;
  currency:          string;
}

// ── Operations metrics ────────────────────────────────────────────────────────

/**
 * Operational health statistics derived from the Operations domain.
 * Zero logic duplication — delegates to shopify-operations-service.
 *
 * Copilot: "statistics.getOperationsMetrics()"
 */
export interface OperationsMetrics {
  failedPayments:    number;
  delayedShipments:  number;
  pendingDeliveries: number;
  returns:           number;
  refunds:           number;
  openIncidents:     number;
  ordersAtRisk:      number;
  criticalAlerts:    number;
}

// ── Trend analysis ────────────────────────────────────────────────────────────

/**
 * Period-over-period comparison of key commercial metrics.
 *
 * Copilot: "statistics.getTrendAnalysis()"
 *
 * Scenarios:
 *   "¿Qué está empeorando?"
 *     → all ComparisonMetrics where direction="down", sort pct asc
 *
 *   "¿Las ventas subieron esta semana?"
 *     → revenue.direction + revenue.pct
 */
export interface TrendAnalysis {
  period:   StatisticsPeriod;
  fromDate: string;   // ISO8601 start of current period
  toDate:   string;   // ISO8601 end of current period
  revenue:  ComparisonMetric;
  orders:   ComparisonMetric;
  aov:      ComparisonMetric;
  units:    ComparisonMetric;
  refunds:  ComparisonMetric;
  returns:  ComparisonMetric;
}

// ── Executive insights ────────────────────────────────────────────────────────

/**
 * A structured executive insight produced by deterministic threshold rules.
 *
 * NON-AI GUARANTEE: Never generated by a language model.
 * Computed from fixed rule evaluation against real metric data.
 * Copilot uses these as inputs to its reasoning, not as outputs.
 *
 * Used by:
 *   - Attention Layer (right rail signal strip)
 *   - Copilot reasoning engine input
 *   - Future: executive council synthesis
 *
 * Copilot read-aloud:
 *   "[{severity.toUpperCase()}] {title}: {description}
 *    Evidencia: {evidence.join(' | ')}
 *    Acción: {suggestedAction}"
 */
export interface ExecutiveInsight {
  /** Unique ID within this analysis run. */
  id:              string;
  category:        InsightCategory;
  title:           string;
  description:     string;
  severity:        InsightSeverity;
  impact:          InsightImpact;
  /** 1 = most urgent. Controls display and Copilot priority queue order. */
  priority:        InsightPriority;
  /** Human-readable data points supporting this insight. */
  evidence:        string[];
  /**
   * Copilot-ready action prompt. Null if purely informational.
   * Copilot MUST show to user and await approval before executing.
   */
  suggestedAction: string | null;
}

// ── Metric health summary ─────────────────────────────────────────────────────

/**
 * Copilot-ready health snapshot covering all key commercial KPIs.
 *
 * Designed for direct Copilot consumption without additional transformation.
 * All HealthedMetric values are pre-classified using deterministic rules.
 *
 * Named properties allow direct Copilot field access:
 *   healthSummary.revenue.metricHealth        → "warning"
 *   healthSummary.failedPayments.healthReason → "2 pedidos con pagos fallidos..."
 *
 * Ranked lists enable priority-sorted responses:
 *   needsAttention[0] → highest-priority KPI requiring action
 *   improving[0]      → best-performing KPI this period
 *
 * Copilot scenarios:
 *   "¿Qué indicadores requieren atención?"
 *     → needsAttention (pre-sorted: critical first, then warning)
 *
 *   "¿Qué mejoró esta semana?"
 *     → improving
 *
 *   "Dame un semáforo de la tienda."
 *     → all 7 named KPIs with metricHealth and healthReason
 *
 *   "¿Dónde debo actuar primero?"
 *     → needsAttention[0].healthReason + needsAttention[0].label
 *
 * NON-AI GUARANTEE: All classifications are rule-based, never AI-generated.
 */
export interface MetricHealthSummary {
  /** Commercial revenue health. */
  revenue:            HealthedMetric;
  /** Order volume health. */
  orders:             HealthedMetric;
  /** Average order value health. */
  averageOrderValue:  HealthedMetric;
  /** Refund amount health (negative metric — rising is bad). */
  refunds:            HealthedMetric;
  /** Return order count health (negative metric — rising is bad). */
  returns:            HealthedMetric;
  /**
   * Failed payment count health.
   * Any > 0 → warning. > 3 → critical.
   * Uses current value vs 0 when no historical data is available.
   */
  failedPayments:     HealthedMetric;
  /**
   * Delayed shipment count health.
   * Any > 0 → warning. > 5 → critical.
   */
  delayedShipments:   HealthedMetric;
  /**
   * KPIs classified as "warning" or "critical", sorted:
   * critical first, then warning, then by deltaPercent (absolute) descending.
   * Pre-sorted — Copilot can use index 0 as the highest-priority signal.
   */
  needsAttention:     HealthedMetric[];
  /**
   * KPIs classified as "good" with direction="up".
   * Sorted by deltaPercent descending — best improvement first.
   */
  improving:          HealthedMetric[];
}

// ── Full overview ─────────────────────────────────────────────────────────────

/**
 * Full executive statistics overview for a Shopify store.
 * Primary output of getOverview() — the top-level analytics contract.
 *
 * Three consumers:
 *   1. Executive workspace (UX statistics screen)
 *   2. Copilot: "Dame el resumen ejecutivo de la tienda."
 *   3. Automation: anomaly detection → alert → Copilot action proposal
 *
 * Copilot: "statistics.getOverview()"
 */
export interface StatisticsOverview {
  sales:       SalesMetrics;
  catalog:     CatalogMetrics;
  promotions:  PromotionMetrics;
  operations:  OperationsMetrics;
  funnel:      FunnelMetrics;
  trends:      TrendAnalysis;
  /** Sorted by priority ascending (1 = most urgent first). */
  insights:    ExecutiveInsight[];
  /**
   * Deterministic health classification for all key KPIs.
   * Primary input for Copilot health queries and right-rail attention signals.
   * NON-AI: all values computed from threshold rules against real metric data.
   */
  healthSummary: MetricHealthSummary;
  generatedAt: string;   // ISO8601
  source:      "shopify";
  period:      StatisticsPeriod;
}
