// AGENTIK-STRATEGIC-FORECASTING-01 — Phase 40: Canonical Forecast Scenarios
// 25 canonical scenarios covering growth, contraction, expansion, transformation, risk, etc.

export interface CanonicalForecastScenario {
  readonly id:           string;
  readonly title:        string;
  readonly description:  string;
  readonly type:         "BEST_CASE" | "EXPECTED_CASE" | "WORST_CASE" | "STRETCH_CASE" | "BLACK_SWAN_CANDIDATE";
  readonly domain:       string;
  readonly horizon:      "SHORT_TERM" | "MEDIUM_TERM" | "LONG_TERM";
  readonly defaultProbability: number; // 0–1 illustrative
  readonly keyRisks:     string[];
  readonly keyOpportunities: string[];
  readonly assumptions:  string[];
  readonly limitations:  string[];
}

export const CANONICAL_FORECAST_SCENARIOS: readonly CanonicalForecastScenario[] = [
  {
    id:            "CFS_CRECIMIENTO_SOSTENIDO",
    title:         "Crecimiento Sostenido — Expansión Orgánica",
    description:   "La organización proyecta crecimiento orgánico sostenido con mejora de márgenes operativos.",
    type:          "BEST_CASE",
    domain:        "FINANCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.30,
    keyRisks:      ["Saturación de mercado", "Competencia agresiva"],
    keyOpportunities: ["Expansión de cartera", "Nuevos segmentos"],
    assumptions:   ["Demanda estable", "Capacidad operativa disponible"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_CONTRACCION_MERCADO",
    title:         "Contracción de Mercado — Presión Competitiva",
    description:   "El mercado objetivo muestra señales de contracción por competencia o cambios en preferencias.",
    type:          "WORST_CASE",
    domain:        "COMMERCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.20,
    keyRisks:      ["Pérdida de cuota de mercado", "Guerra de precios"],
    keyOpportunities: ["Diferenciación de oferta", "Nuevos canales"],
    assumptions:   ["Competidores mantienen agresividad"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_EXPANSION_GEOGRAFICA",
    title:         "Expansión Geográfica — Nuevos Territorios",
    description:   "La organización evalúa apertura de operaciones en nuevas regiones o países.",
    type:          "STRETCH_CASE",
    domain:        "STRATEGIC",
    horizon:       "LONG_TERM",
    defaultProbability: 0.15,
    keyRisks:      ["Riesgo regulatorio", "Complejidad operativa"],
    keyOpportunities: ["Diversificación de ingresos", "Economías de escala"],
    assumptions:   ["Acceso a capital", "Talento disponible"],
    limitations:   ["suggestedOnly: true", "Requiere validación estratégica"],
  },
  {
    id:            "CFS_TRANSFORMACION_DIGITAL",
    title:         "Transformación Digital — Automatización Operativa",
    description:   "Iniciativa de transformación digital con impacto transversal en operaciones y clientes.",
    type:          "EXPECTED_CASE",
    domain:        "TECHNOLOGY",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.50,
    keyRisks:      ["Resistencia al cambio", "Costos de implementación"],
    keyOpportunities: ["Eficiencia operativa", "Mejora de experiencia cliente"],
    assumptions:   ["Presupuesto aprobado", "Patrocinio ejecutivo"],
    limitations:   ["suggestedOnly: true", "Depende de ejecución"],
  },
  {
    id:            "CFS_CRISIS_LIQUIDEZ",
    title:         "Crisis de Liquidez — Presión de Flujo de Caja",
    description:   "Escenario de presión severa en liquidez operativa con riesgo de incumplimiento.",
    type:          "WORST_CASE",
    domain:        "FINANCIAL",
    horizon:       "SHORT_TERM",
    defaultProbability: 0.10,
    keyRisks:      ["Incumplimiento de obligaciones", "Pérdida de confianza"],
    keyOpportunities: ["Reestructuración de deuda", "Desinversión de activos"],
    assumptions:   ["Sin acceso a crédito adicional"],
    limitations:   ["suggestedOnly: true", "Escenario de baja probabilidad y alto impacto"],
  },
  {
    id:            "CFS_ADQUISICION_ESTRATEGICA",
    title:         "Adquisición Estratégica — Consolidación Sectorial",
    description:   "Oportunidad de adquisición de un competidor o empresa complementaria para fortalecer posición.",
    type:          "STRETCH_CASE",
    domain:        "STRATEGIC",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.12,
    keyRisks:      ["Sobreprecio", "Integración fallida"],
    keyOpportunities: ["Consolidación de mercado", "Sinergias operativas"],
    assumptions:   ["Due diligence completa", "Financiamiento disponible"],
    limitations:   ["suggestedOnly: true", "Requiere aprobación de junta"],
  },
  {
    id:            "CFS_PERDIDA_CLIENTE_CLAVE",
    title:         "Pérdida de Cliente Clave — Concentración de Ingresos",
    description:   "Escenario donde la pérdida de uno o más clientes clave impacta materialmente los ingresos.",
    type:          "WORST_CASE",
    domain:        "COMMERCIAL",
    horizon:       "SHORT_TERM",
    defaultProbability: 0.15,
    keyRisks:      ["Impacto en flujo de caja", "Reducción de capacidad operativa"],
    keyOpportunities: ["Diversificación de cartera", "Nuevos clientes"],
    assumptions:   ["Concentración de ingresos en pocos clientes"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_INNOVACION_PRODUCTO",
    title:         "Innovación de Producto — Lanzamiento Nueva Línea",
    description:   "Lanzamiento de nueva línea de productos o servicios con potencial de captura de mercado.",
    type:          "BEST_CASE",
    domain:        "COMMERCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.28,
    keyRisks:      ["Fracaso de adopción", "Costos de go-to-market"],
    keyOpportunities: ["Nuevos ingresos", "Diferenciación competitiva"],
    assumptions:   ["Validación de mercado completada"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_RIESGO_REGULATORIO",
    title:         "Riesgo Regulatorio — Cambio Normativo",
    description:   "Cambios regulatorios materiales que requieren adaptación operativa y legal.",
    type:          "WORST_CASE",
    domain:        "REGULATORY",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.18,
    keyRisks:      ["Multas y sanciones", "Paralización de operaciones"],
    keyOpportunities: ["Cumplimiento anticipado como ventaja", "Confianza de mercado"],
    assumptions:   ["Regulación más restrictiva aprobada"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_ESCALABILIDAD_OPERATIVA",
    title:         "Escalabilidad Operativa — Crecimiento de Capacidad",
    description:   "Inversión en infraestructura y procesos para soportar crecimiento proyectado.",
    type:          "EXPECTED_CASE",
    domain:        "OPERATIONAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.45,
    keyRisks:      ["Sobrecapacidad", "Costos fijos elevados"],
    keyOpportunities: ["Eficiencia a escala", "Mayor velocidad de entrega"],
    assumptions:   ["Demanda creciente confirmada"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_RIESGO_TALENTO",
    title:         "Riesgo de Talento — Rotación o Escasez Clave",
    description:   "Pérdida o escasez de talento crítico con impacto en capacidad de ejecución.",
    type:          "WORST_CASE",
    domain:        "TALENT",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.22,
    keyRisks:      ["Pérdida de conocimiento crítico", "Retrasos en proyectos"],
    keyOpportunities: ["Rediseño de propuesta de valor al empleado"],
    assumptions:   ["Mercado laboral competitivo"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_ALIANZA_ESTRATEGICA",
    title:         "Alianza Estratégica — Joint Venture o Partnership",
    description:   "Formación de alianza estratégica para captura de oportunidades compartidas.",
    type:          "BEST_CASE",
    domain:        "STRATEGIC",
    horizon:       "LONG_TERM",
    defaultProbability: 0.20,
    keyRisks:      ["Divergencia de objetivos", "Dependencia del socio"],
    keyOpportunities: ["Acceso a nuevos mercados", "Capacidades complementarias"],
    assumptions:   ["Alineación estratégica confirmada"],
    limitations:   ["suggestedOnly: true", "Requiere negociación formal"],
  },
  {
    id:            "CFS_PRESION_MARGINAL",
    title:         "Presión Marginal — Compresión de Márgenes",
    description:   "Presión estructural sobre márgenes por costos crecientes y competencia en precios.",
    type:          "WORST_CASE",
    domain:        "FINANCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.30,
    keyRisks:      ["Reducción de rentabilidad", "Deterioro de EBITDA"],
    keyOpportunities: ["Optimización de costos", "Mejora de mezcla de productos"],
    assumptions:   ["Inflación de costos sostenida"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_DISRUPCION_TECNOLOGICA",
    title:         "Disrupción Tecnológica — Nuevos Competidores Digitales",
    description:   "Entrada de competidores tecnológicos nativos que amenazan el modelo de negocio actual.",
    type:          "BLACK_SWAN_CANDIDATE",
    domain:        "TECHNOLOGY",
    horizon:       "LONG_TERM",
    defaultProbability: 0.08,
    keyRisks:      ["Obsolescencia del modelo", "Pérdida acelerada de mercado"],
    keyOpportunities: ["Transformación hacia modelo digital", "Nuevas partnerships"],
    assumptions:   ["Tecnología disruptiva disponible y adoptada"],
    limitations:   ["suggestedOnly: true", "Escenario de cola de alta incertidumbre"],
  },
  {
    id:            "CFS_CONSOLIDACION_SECTOR",
    title:         "Consolidación Sectorial — Ola de M&A",
    description:   "El sector experimenta consolidación acelerada con fusiones y adquisiciones.",
    type:          "EXPECTED_CASE",
    domain:        "MARKET",
    horizon:       "LONG_TERM",
    defaultProbability: 0.40,
    keyRisks:      ["Presión de competidores más grandes", "Riesgo de absorción"],
    keyOpportunities: ["Posicionamiento como adquirente", "Prima de valor al ser adquirido"],
    assumptions:   ["Acceso a capital en el sector"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_CICLO_MACRO_ADVERSO",
    title:         "Ciclo Macroeconómico Adverso — Desaceleración",
    description:   "Desaceleración macroeconómica con impacto en demanda y condiciones de crédito.",
    type:          "WORST_CASE",
    domain:        "FINANCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.18,
    keyRisks:      ["Reducción de demanda", "Restricción de crédito"],
    keyOpportunities: ["Posicionamiento como opción de valor", "Eficiencia operativa"],
    assumptions:   ["Ciclo macro negativo de 12+ meses"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_LIDERAZGO_MERCADO",
    title:         "Liderazgo de Mercado — Posicionamiento Premium",
    description:   "La organización consolida posición de liderazgo con diferenciación y pricing power.",
    type:          "BEST_CASE",
    domain:        "COMMERCIAL",
    horizon:       "LONG_TERM",
    defaultProbability: 0.22,
    keyRisks:      ["Rigidez estratégica", "Dependencia de marca"],
    keyOpportunities: ["Premiumización de oferta", "Lealtad de clientes"],
    assumptions:   ["Diferenciación sostenible"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_RIESGO_CIBERSEGURIDAD",
    title:         "Riesgo de Ciberseguridad — Incidente Mayor",
    description:   "Materialización de un incidente de ciberseguridad con impacto operativo y reputacional.",
    type:          "BLACK_SWAN_CANDIDATE",
    domain:        "TECHNOLOGY",
    horizon:       "SHORT_TERM",
    defaultProbability: 0.05,
    keyRisks:      ["Pérdida de datos", "Interrupción operativa", "Daño reputacional"],
    keyOpportunities: ["Fortalecimiento de infraestructura de seguridad"],
    assumptions:   ["Exposición en sistemas críticos"],
    limitations:   ["suggestedOnly: true", "Probabilidad baja pero impacto severo"],
  },
  {
    id:            "CFS_EFICIENCIA_OPERATIVA",
    title:         "Eficiencia Operativa — Optimización de Procesos",
    description:   "Programa de mejora de eficiencia operativa con reducción de costos y mejora de calidad.",
    type:          "EXPECTED_CASE",
    domain:        "OPERATIONAL",
    horizon:       "SHORT_TERM",
    defaultProbability: 0.55,
    keyRisks:      ["Resistencia interna", "Pérdida de calidad"],
    keyOpportunities: ["Ahorro de costos", "Mayor agilidad"],
    assumptions:   ["Patrocinio ejecutivo y recursos disponibles"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_DIVERSIFICACION_INGRESOS",
    title:         "Diversificación de Ingresos — Nuevas Fuentes",
    description:   "Estrategia de diversificación de fuentes de ingresos para reducir concentración y riesgo.",
    type:          "STRETCH_CASE",
    domain:        "FINANCIAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.18,
    keyRisks:      ["Dilución de foco", "Inversión sin retorno"],
    keyOpportunities: ["Resiliencia de ingresos", "Nuevos mercados"],
    assumptions:   ["Capacidades disponibles para diversificación"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_GOBIERNO_CORPORATIVO",
    title:         "Fortalecimiento de Gobierno Corporativo",
    description:   "Iniciativa de mejora de gobernanza corporativa con impacto en confianza de inversores.",
    type:          "BEST_CASE",
    domain:        "GOVERNANCE",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.35,
    keyRisks:      ["Costo de cumplimiento", "Resistencia a controles"],
    keyOpportunities: ["Mayor acceso a capital", "Confianza institucional"],
    assumptions:   ["Compromiso de junta y accionistas"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_EXPANSION_PRODUCTO_DIGITAL",
    title:         "Expansión de Producto Digital — Ecosistema",
    description:   "Construcción de ecosistema digital alrededor del producto principal para crear red de valor.",
    type:          "STRETCH_CASE",
    domain:        "TECHNOLOGY",
    horizon:       "LONG_TERM",
    defaultProbability: 0.14,
    keyRisks:      ["Complejidad tecnológica", "Adopción de plataforma"],
    keyOpportunities: ["Efecto de red", "Nuevas líneas de ingresos"],
    assumptions:   ["Base de clientes suficiente para ecosistema"],
    limitations:   ["suggestedOnly: true", "Requiere inversión tecnológica sostenida"],
  },
  {
    id:            "CFS_RIESGO_CONCENTRACION_PROVEEDOR",
    title:         "Riesgo de Concentración de Proveedor — Dependencia Crítica",
    description:   "Alta dependencia de uno o pocos proveedores críticos con riesgo de disrupción en cadena.",
    type:          "WORST_CASE",
    domain:        "OPERATIONAL",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.20,
    keyRisks:      ["Disrupción de suministro", "Incremento de costos"],
    keyOpportunities: ["Diversificación de proveedores", "Integración vertical"],
    assumptions:   ["Proveedor clave con problemas financieros o de capacidad"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_RECUPERACION_POST_CRISIS",
    title:         "Recuperación Post-Crisis — Rebote Operativo",
    description:   "Escenario de recuperación acelerada tras un período de adversidad operativa.",
    type:          "BEST_CASE",
    domain:        "OPERATIONAL",
    horizon:       "SHORT_TERM",
    defaultProbability: 0.32,
    keyRisks:      ["Recaída", "Capacidad limitada de respuesta"],
    keyOpportunities: ["Reactivación de demanda reprimida", "Eficiencia post-reestructuración"],
    assumptions:   ["Resolución del factor de crisis"],
    limitations:   ["suggestedOnly: true", "Proyección orientativa"],
  },
  {
    id:            "CFS_IMPACTO_GEOPOLITICO",
    title:         "Impacto Geopolítico — Volatilidad Regional",
    description:   "Eventos geopolíticos que generan volatilidad en mercados, cadenas de suministro y demanda.",
    type:          "BLACK_SWAN_CANDIDATE",
    domain:        "RISK",
    horizon:       "MEDIUM_TERM",
    defaultProbability: 0.07,
    keyRisks:      ["Disrupción de operaciones", "Volatilidad de tipo de cambio"],
    keyOpportunities: ["Reposicionamiento geográfico", "Arbitraje de condiciones"],
    assumptions:   ["Escalada de tensiones regionales"],
    limitations:   ["suggestedOnly: true", "Alta incertidumbre inherente"],
  },
] as const;

export function getCanonicalForecastScenario(
  id: string
): CanonicalForecastScenario | undefined {
  return CANONICAL_FORECAST_SCENARIOS.find((s) => s.id === id);
}

export function getCanonicalScenariosByDomain(
  domain: string
): readonly CanonicalForecastScenario[] {
  return CANONICAL_FORECAST_SCENARIOS.filter((s) => s.domain === domain);
}

export function getCanonicalScenariosByType(
  type: CanonicalForecastScenario["type"]
): readonly CanonicalForecastScenario[] {
  return CANONICAL_FORECAST_SCENARIOS.filter((s) => s.type === type);
}
