// AGENTIK-ENTERPRISE-DIRECTION-SYSTEM-01 — Phase 45: Canonical Direction Scenarios
// 30+ strategic direction scenarios. All suggestedOnly implied in limitations.

export interface CanonicalDirectionScenario {
  readonly id:              string; // CDS_XXX
  readonly title:           string;
  readonly domain:          string;
  readonly horizon:         string;
  readonly alignmentLevel:  string; // ALIGNED | PARTIALLY_ALIGNED | MISALIGNED | UNDER_REVIEW
  readonly northStarTheme:  string;
  readonly description:     string;
  readonly keyRisks:        string[];
  readonly opportunities:   string[];
  readonly limitations:     string[];
}

export const CANONICAL_DIRECTION_SCENARIOS: readonly CanonicalDirectionScenario[] = [
  {
    id:             "CDS_001",
    title:          "Crecimiento acelerado con riesgo de sobrecarga operativa",
    domain:         "GROWTH",
    horizon:        "SHORT_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Expansión de ingresos",
    description:    "El crecimiento podría superar la capacidad operativa de soportar la demanda.",
    keyRisks:       ["Capacidad operativa insuficiente", "Deterioro en calidad del servicio"],
    opportunities:  ["Captura de participación de mercado", "Economías de escala potenciales"],
    limitations:    ["suggestedOnly: true", "Proyección basada en datos históricos limitados"],
  },
  {
    id:             "CDS_002",
    title:          "Contracción de márgenes con presión de costos",
    domain:         "PROFITABILITY",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Rentabilidad sostenible",
    description:    "Los márgenes podrían comprimirse por aumento de costos sin poder trasladarlos al cliente.",
    keyRisks:       ["Erosión de rentabilidad", "Competencia en precios"],
    opportunities:  ["Eficiencia operativa", "Revisión de estructura de precios"],
    limitations:    ["suggestedOnly: true", "Datos de costos actuales no verificados independientemente"],
  },
  {
    id:             "CDS_003",
    title:          "Transformación digital exitosa con adopción organizacional",
    domain:         "TECHNOLOGY",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Diferenciación tecnológica",
    description:    "La digitalización podría crear ventajas competitivas sostenibles si hay adopción interna.",
    keyRisks:       ["Resistencia al cambio", "Costos de implementación superiores a lo proyectado"],
    opportunities:  ["Automatización y eficiencia", "Nuevas propuestas de valor digitales"],
    limitations:    ["suggestedOnly: true", "Éxito depende de factores culturales y de gestión del cambio"],
  },
  {
    id:             "CDS_004",
    title:          "Disruption de mercado por competidor emergente",
    domain:         "MARKET",
    horizon:        "SHORT_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Posicionamiento competitivo",
    description:    "Un competidor con modelo disruptivo podría erosionar la posición de mercado.",
    keyRisks:       ["Pérdida de clientes clave", "Presión en precios"],
    opportunities:  ["Aceleración de innovación propia", "Diferenciación en servicio"],
    limitations:    ["suggestedOnly: true", "Inteligencia competitiva no incluida en el análisis"],
  },
  {
    id:             "CDS_005",
    title:          "Consolidación de posición con foco en retención",
    domain:         "OPERATIONS",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Excelencia operacional",
    description:    "Estrategia defensiva de consolidar base de clientes con alta retención.",
    keyRisks:       ["Bajo crecimiento neto", "Saturación del mercado actual"],
    opportunities:  ["NPS elevado y referidos", "Upselling y cross-selling"],
    limitations:    ["suggestedOnly: true", "Métricas de retención actuales no validadas externamente"],
  },
  {
    id:             "CDS_006",
    title:          "Crisis de talento con riesgo de pérdida de conocimiento clave",
    domain:         "TALENT",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Capital humano estratégico",
    description:    "La rotación podría generar pérdida de conocimiento crítico y deterioro de capacidades.",
    keyRisks:       ["Pérdida de talento senior", "Curva de aprendizaje prolongada"],
    opportunities:  ["Rediseño de propuesta de valor al empleado", "Programa de sucesión"],
    limitations:    ["suggestedOnly: true", "Datos de rotación recientes requeridos para validación"],
  },
  {
    id:             "CDS_007",
    title:          "Expansión geográfica con riesgo regulatorio",
    domain:         "GROWTH",
    horizon:        "LONG_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Expansión territorial",
    description:    "La expansión a nuevas geografías podría traer riesgos regulatorios y operativos.",
    keyRisks:       ["Complejidad regulatoria local", "Costos de establecimiento"],
    opportunities:  ["Nuevos mercados con menor competencia", "Diversificación de ingresos"],
    limitations:    ["suggestedOnly: true", "Análisis regulatorio específico por geografía requerido"],
  },
  {
    id:             "CDS_008",
    title:          "Innovación incremental vs. transformación radical",
    domain:         "INNOVATION",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Capacidad de innovación",
    description:    "La organización enfrenta una bifurcación entre mejorar lo existente o reinventarse.",
    keyRisks:       ["Quedarse rezagado tecnológicamente", "Sobre-inversión en innovación"],
    opportunities:  ["Liderazgo en nuevo nicho", "Protección de márgenes actuales"],
    limitations:    ["suggestedOnly: true", "Decisión requiere análisis financiero y estratégico profundo"],
  },
  {
    id:             "CDS_009",
    title:          "Escasez de capital en período de crecimiento",
    domain:         "PROFITABILITY",
    horizon:        "SHORT_TERM",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Sostenibilidad financiera",
    description:    "El crecimiento podría estar limitado por restricciones de capital de trabajo.",
    keyRisks:       ["Tensión de liquidez", "Freno a inversiones estratégicas"],
    opportunities:  ["Optimización del ciclo de caja", "Estructuración de financiamiento"],
    limitations:    ["suggestedOnly: true", "Proyecciones de flujo de caja deben validarse"],
  },
  {
    id:             "CDS_010",
    title:          "Alianza estratégica transformadora",
    domain:         "MARKET",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Ecosistema de valor",
    description:    "Una alianza estratégica podría acelerar el acceso a nuevas capacidades y mercados.",
    keyRisks:       ["Dependencia del socio", "Dilución de identidad de marca"],
    opportunities:  ["Capacidades complementarias", "Acceso a nuevos segmentos"],
    limitations:    ["suggestedOnly: true", "Due diligence de socios potenciales no incluido"],
  },
  {
    id:             "CDS_011",
    title:          "Reconfiguración del modelo de distribución",
    domain:         "OPERATIONS",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Eficiencia de go-to-market",
    description:    "Rediseño de canales de distribución para mejorar alcance y reducir costos.",
    keyRisks:       ["Resistencia de canales existentes", "Pérdida temporal de ventas"],
    opportunities:  ["Mayor control de la relación con el cliente", "Mejor márgenes directos"],
    limitations:    ["suggestedOnly: true", "Análisis de canales actuales y potenciales requerido"],
  },
  {
    id:             "CDS_012",
    title:          "Crisis de reputación con impacto estratégico",
    domain:         "RISK",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Gestión de riesgos reputacionales",
    description:    "Un evento de reputación podría afectar la relación con clientes y socios clave.",
    keyRisks:       ["Pérdida de contratos", "Deterioro de marca empleadora"],
    opportunities:  ["Oportunidad de reforma y demostración de valores", "Transparencia como diferenciador"],
    limitations:    ["suggestedOnly: true", "Contexto específico del evento no analizado"],
  },
  {
    id:             "CDS_013",
    title:          "Adopción de IA como motor de eficiencia",
    domain:         "TECHNOLOGY",
    horizon:        "SHORT_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Automatización inteligente",
    description:    "La integración de IA podría generar ganancias de eficiencia y nuevas capacidades.",
    keyRisks:       ["Dependencia tecnológica", "Brechas de talento en IA"],
    opportunities:  ["Reducción de costos operativos", "Mejora en calidad de decisiones"],
    limitations:    ["suggestedOnly: true", "Casos de uso específicos requieren validación técnica"],
  },
  {
    id:             "CDS_014",
    title:          "Concentración de ingresos en pocos clientes",
    domain:         "RISK",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Diversificación de base de clientes",
    description:    "Alta dependencia de pocos clientes genera riesgo de concentración significativo.",
    keyRisks:       ["Pérdida de cliente principal", "Poder de negociación desfavorable"],
    opportunities:  ["Programa de diversificación de cartera", "Desarrollo de nuevos segmentos"],
    limitations:    ["suggestedOnly: true", "Datos de concentración por cliente requeridos"],
  },
  {
    id:             "CDS_015",
    title:          "Gobernanza corporativa para escala",
    domain:         "GOVERNANCE",
    horizon:        "LONG_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Madurez organizacional",
    description:    "La estructura de gobernanza actual podría ser insuficiente para la siguiente etapa de crecimiento.",
    keyRisks:       ["Toma de decisiones lenta", "Falta de rendición de cuentas"],
    opportunities:  ["Profesionalización de dirección", "Mejora en eficiencia de decisiones"],
    limitations:    ["suggestedOnly: true", "Diagnóstico de gobernanza actual requerido"],
  },
  {
    id:             "CDS_016",
    title:          "Diferenciación por sostenibilidad",
    domain:         "INNOVATION",
    horizon:        "LONG_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Propuesta de valor sostenible",
    description:    "La sostenibilidad como diferenciador estratégico en mercados con compradores conscientes.",
    keyRisks:       ["Greenwashing y riesgos reputacionales", "Costos de certificación"],
    opportunities:  ["Acceso a nuevos segmentos ESG", "Eficiencia en recursos"],
    limitations:    ["suggestedOnly: true", "Percepción de clientes sobre sostenibilidad requiere validación"],
  },
  {
    id:             "CDS_017",
    title:          "Expansión de capacidad productiva anticipatoria",
    domain:         "OPERATIONS",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Escalabilidad operativa",
    description:    "Inversión en capacidad antes de que la demanda lo requiera como ventaja competitiva.",
    keyRisks:       ["Capacidad ociosa si demanda no se materializa", "Costo de capital elevado"],
    opportunities:  ["Tiempo de respuesta superior", "Captación de clientes con necesidades urgentes"],
    limitations:    ["suggestedOnly: true", "Proyecciones de demanda con alta incertidumbre"],
  },
  {
    id:             "CDS_018",
    title:          "Penetración de segmento premium",
    domain:         "MARKET",
    horizon:        "SHORT_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Posicionamiento premium",
    description:    "Reposicionamiento hacia segmentos de mayor valor y menor sensibilidad al precio.",
    keyRisks:       ["Pérdida de base de clientes actuales", "Requerimientos de calidad más exigentes"],
    opportunities:  ["Mejora de márgenes", "Menor competencia en precio"],
    limitations:    ["suggestedOnly: true", "Disposición a pagar del segmento premium debe validarse"],
  },
  {
    id:             "CDS_019",
    title:          "Retención de clientes como estrategia defensiva",
    domain:         "MARKET",
    horizon:        "IMMEDIATE",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Lealtad de clientes",
    description:    "En mercados competitivos, la retención puede ser más rentable que la adquisición.",
    keyRisks:       ["Costo de programas de retención", "Saturación de beneficios"],
    opportunities:  ["Reducción de churn", "Incremento de LTV"],
    limitations:    ["suggestedOnly: true", "Métricas de churn actuales requeridas para calibrar"],
  },
  {
    id:             "CDS_020",
    title:          "Integración vertical como ventaja competitiva",
    domain:         "OPERATIONS",
    horizon:        "LONG_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Control de cadena de valor",
    description:    "La integración vertical podría mejorar márgenes y calidad, pero aumenta complejidad.",
    keyRisks:       ["Complejidad operativa incrementada", "Capital inmovilizado"],
    opportunities:  ["Mejor control de calidad", "Eliminación de intermediarios"],
    limitations:    ["suggestedOnly: true", "Análisis de capacidades actuales y requeridas necesario"],
  },
  {
    id:             "CDS_021",
    title:          "Reinvención del modelo de atención al cliente",
    domain:         "INNOVATION",
    horizon:        "SHORT_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Experiencia de cliente",
    description:    "Rediseño de la forma en que se atiende al cliente como ventaja competitiva.",
    keyRisks:       ["Resistencia interna al cambio", "Inversión sin retorno claro"],
    opportunities:  ["NPS elevado y diferenciación", "Reducción de costos de atención"],
    limitations:    ["suggestedOnly: true", "Voz del cliente actual debe guiar el diseño"],
  },
  {
    id:             "CDS_022",
    title:          "Formalización de procesos de innovación",
    domain:         "INNOVATION",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Innovación sistemática",
    description:    "Establecer estructuras formales para capturar y desarrollar ideas de innovación.",
    keyRisks:       ["Burocracia que mata la innovación", "Expectativas no gestionadas"],
    opportunities:  ["Pipeline de innovación predecible", "Cultura de experimentación"],
    limitations:    ["suggestedOnly: true", "Cultura actual de innovación debe evaluarse primero"],
  },
  {
    id:             "CDS_023",
    title:          "Respuesta a cambio regulatorio inminente",
    domain:         "GOVERNANCE",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Cumplimiento proactivo",
    description:    "Un cambio regulatorio próximo requiere adaptación rápida de operaciones.",
    keyRisks:       ["Sanciones y penalizaciones", "Costo de adaptación apresurada"],
    opportunities:  ["Ventaja de ser primero en cumplir", "Relación con reguladores"],
    limitations:    ["suggestedOnly: true", "Marco regulatorio específico no analizado en detalle"],
  },
  {
    id:             "CDS_024",
    title:          "Crisis de liquidez por crecimiento no financiado",
    domain:         "PROFITABILITY",
    horizon:        "IMMEDIATE",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Sostenibilidad financiera",
    description:    "El crecimiento acelerado podría generar una crisis de caja si no está bien financiado.",
    keyRisks:       ["Insolvencia técnica", "Pérdida de confianza de acreedores"],
    opportunities:  ["Negociación de líneas de crédito", "Optimización de ciclo de cobros"],
    limitations:    ["suggestedOnly: true", "Proyecciones de flujo de caja deben ser verificadas"],
  },
  {
    id:             "CDS_025",
    title:          "Adquisición de competidor como acelerador",
    domain:         "GROWTH",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Crecimiento inorgánico",
    description:    "Una adquisición estratégica podría acelerar capacidades y participación de mercado.",
    keyRisks:       ["Integración cultural y operativa", "Precio de adquisición excesivo"],
    opportunities:  ["Aceleración de crecimiento", "Eliminación de competidor"],
    limitations:    ["suggestedOnly: true", "Due diligence financiero y estratégico requerido"],
  },
  {
    id:             "CDS_026",
    title:          "Riesgo tecnológico por deuda técnica acumulada",
    domain:         "TECHNOLOGY",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "MISALIGNED",
    northStarTheme: "Modernización tecnológica",
    description:    "La deuda técnica acumulada podría limitar la capacidad de innovar y escalar.",
    keyRisks:       ["Interrupciones de servicio", "Costo de refactorización creciente"],
    opportunities:  ["Modernización como ventaja futura", "Reducción de costos de mantenimiento"],
    limitations:    ["suggestedOnly: true", "Audit técnico detallado necesario para priorizar"],
  },
  {
    id:             "CDS_027",
    title:          "Reconfiguración del equipo directivo",
    domain:         "TALENT",
    horizon:        "SHORT_TERM",
    alignmentLevel: "UNDER_REVIEW",
    northStarTheme: "Liderazgo estratégico",
    description:    "Cambios en el liderazgo pueden afectar la ejecución de la estrategia.",
    keyRisks:       ["Pérdida de continuidad estratégica", "Incertidumbre organizacional"],
    opportunities:  ["Renovación de energía y perspectivas", "Nuevas capacidades de liderazgo"],
    limitations:    ["suggestedOnly: true", "Contexto específico de cambio directivo no disponible"],
  },
  {
    id:             "CDS_028",
    title:          "Modelo de trabajo híbrido como ventaja de talento",
    domain:         "TALENT",
    horizon:        "MEDIUM_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Flexibilidad laboral estratégica",
    description:    "Un modelo de trabajo flexible podría mejorar atracción y retención de talento.",
    keyRisks:       ["Pérdida de cultura presencial", "Gestión de equipos distribuidos"],
    opportunities:  ["Acceso a talento global", "Reducción de costos de oficina"],
    limitations:    ["suggestedOnly: true", "Preferencias de empleados actuales deben consultarse"],
  },
  {
    id:             "CDS_029",
    title:          "Consolidación de cartera de clientes rentables",
    domain:         "PROFITABILITY",
    horizon:        "SHORT_TERM",
    alignmentLevel: "ALIGNED",
    northStarTheme: "Rentabilidad por cliente",
    description:    "Foco en clientes de alta rentabilidad y reducción de clientes que generan pérdidas.",
    keyRisks:       ["Impacto en ingresos totales", "Dependencia de pocos clientes rentables"],
    opportunities:  ["Mejora de márgenes globales", "Liberación de capacidad para mejores clientes"],
    limitations:    ["suggestedOnly: true", "Análisis de rentabilidad por cliente requerido"],
  },
  {
    id:             "CDS_030",
    title:          "Construcción de ventaja competitiva sostenible",
    domain:         "CROSS_DOMAIN",
    horizon:        "LONG_TERM",
    alignmentLevel: "PARTIALLY_ALIGNED",
    northStarTheme: "Ventaja competitiva duradera",
    description:    "Identificación y construcción de recursos estratégicos difíciles de replicar.",
    keyRisks:       ["Tiempo de construcción largo", "Cambio en factores de éxito del mercado"],
    opportunities:  ["Posicionamiento diferenciado", "Barreras de entrada para competidores"],
    limitations:    ["suggestedOnly: true", "Recursos estratégicos actuales deben inventariarse"],
  },
] as const;
