// AGENTIK-ENTERPRISE-DIRECTION-SYSTEM-01 — Phase 44: Canonical Direction Cases
// 30 canonical strategic direction cases. All suggestedOnly: true in limitations.

export interface CanonicalDirectionCase {
  readonly id:          string; // CDC_XXX
  readonly title:       string;
  readonly domain:      string;
  readonly horizon:     string;
  readonly status:      string;
  readonly description: string;
  readonly limitations: string[];
}

export const CANONICAL_DIRECTION_CASES: readonly CanonicalDirectionCase[] = [
  {
    id:          "CDC_001",
    title:       "Expansión a nuevos mercados",
    domain:      "GROWTH",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "La organización podría expandirse a nuevos mercados con base en señales de demanda emergentes.",
    limitations: ["suggestedOnly: true", "Requiere validación ejecutiva y análisis de mercado profundo"],
  },
  {
    id:          "CDC_002",
    title:       "Optimización de márgenes operativos",
    domain:      "PROFITABILITY",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Oportunidad potencial de mejorar márgenes mediante eficiencia operativa.",
    limitations: ["suggestedOnly: true", "Impacto real depende de datos financieros detallados"],
  },
  {
    id:          "CDC_003",
    title:       "Transformación digital de operaciones",
    domain:      "TECHNOLOGY",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "La modernización tecnológica podría generar ventajas competitivas sostenibles.",
    limitations: ["suggestedOnly: true", "Requiere evaluación de capacidades técnicas actuales"],
  },
  {
    id:          "CDC_004",
    title:       "Consolidación de liderazgo de mercado",
    domain:      "MARKET",
    horizon:     "MEDIUM_TERM",
    status:      "ALIGNED",
    description: "Posicionamiento estratégico para consolidar participación en el mercado principal.",
    limitations: ["suggestedOnly: true", "Análisis competitivo externo no incluido"],
  },
  {
    id:          "CDC_005",
    title:       "Reducción de costos estructurales",
    domain:      "EFFICIENCY",
    horizon:     "SHORT_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Identificación de costos que podrían optimizarse sin afectar la calidad del servicio.",
    limitations: ["suggestedOnly: true", "Requiere análisis detallado de estructura de costos"],
  },
  {
    id:          "CDC_006",
    title:       "Innovación en modelo de negocio",
    domain:      "INNOVATION",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "Exploración de nuevos modelos de generación de valor y monetización.",
    limitations: ["suggestedOnly: true", "Alta incertidumbre — validación de mercado necesaria"],
  },
  {
    id:          "CDC_007",
    title:       "Fortalecimiento de gobierno corporativo",
    domain:      "GOVERNANCE",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Mejora en estructuras de gobernanza para soportar crecimiento organizacional.",
    limitations: ["suggestedOnly: true", "Requiere consultoría especializada en gobierno"],
  },
  {
    id:          "CDC_008",
    title:       "Gestión de riesgos sistémicos",
    domain:      "RISK",
    horizon:     "IMMEDIATE",
    status:      "MISALIGNED",
    description: "Atención prioritaria a riesgos que podrían afectar la continuidad operacional.",
    limitations: ["suggestedOnly: true", "Evaluación de riesgos específicos requerida"],
  },
  {
    id:          "CDC_009",
    title:       "Desarrollo de talento estratégico",
    domain:      "TALENT",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Inversión en capacidades humanas críticas para la estrategia de crecimiento.",
    limitations: ["suggestedOnly: true", "Requiere diagnóstico de brechas de talento"],
  },
  {
    id:          "CDC_010",
    title:       "Internacionalización de operaciones",
    domain:      "GROWTH",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "Expansión internacional como palanca de crecimiento de largo plazo.",
    limitations: ["suggestedOnly: true", "Requiere análisis de mercados objetivo y regulatorios"],
  },
  {
    id:          "CDC_011",
    title:       "Optimización de cadena de suministro",
    domain:      "OPERATIONS",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Mejora en eficiencia y resiliencia de la cadena de suministro.",
    limitations: ["suggestedOnly: true", "Impacto sujeto a condiciones de proveedores"],
  },
  {
    id:          "CDC_012",
    title:       "Diversificación de portafolio",
    domain:      "GROWTH",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Expansión de líneas de productos o servicios para reducir concentración de riesgo.",
    limitations: ["suggestedOnly: true", "Requiere análisis de capacidad de inversión"],
  },
  {
    id:          "CDC_013",
    title:       "Digitalización de canales de venta",
    domain:      "TECHNOLOGY",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Transformación de canales comerciales hacia plataformas digitales.",
    limitations: ["suggestedOnly: true", "Requiere evaluación de comportamiento del cliente"],
  },
  {
    id:          "CDC_014",
    title:       "Gestión de liquidez estratégica",
    domain:      "PROFITABILITY",
    horizon:     "IMMEDIATE",
    status:      "PARTIALLY_ALIGNED",
    description: "Optimización del ciclo de caja y gestión de capital de trabajo.",
    limitations: ["suggestedOnly: true", "Datos financieros actualizados requeridos"],
  },
  {
    id:          "CDC_015",
    title:       "Construcción de marca empleadora",
    domain:      "TALENT",
    horizon:     "MEDIUM_TERM",
    status:      "UNDER_REVIEW",
    description: "Desarrollo de propuesta de valor para atracción y retención de talento.",
    limitations: ["suggestedOnly: true", "Requiere benchmarking de mercado laboral"],
  },
  {
    id:          "CDC_016",
    title:       "Alianzas estratégicas y ecosistema",
    domain:      "MARKET",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Construcción de alianzas para ampliar capacidades y acceso a mercados.",
    limitations: ["suggestedOnly: true", "Due diligence de socios potenciales necesario"],
  },
  {
    id:          "CDC_017",
    title:       "Transformación cultural organizacional",
    domain:      "TALENT",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "Evolución de la cultura organizacional hacia mayor agilidad e innovación.",
    limitations: ["suggestedOnly: true", "Proceso de largo plazo con alta complejidad"],
  },
  {
    id:          "CDC_018",
    title:       "Sostenibilidad y ESG",
    domain:      "GOVERNANCE",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "Integración de criterios ESG en la estrategia y operaciones.",
    limitations: ["suggestedOnly: true", "Marco regulatorio específico requerido"],
  },
  {
    id:          "CDC_019",
    title:       "Automatización de procesos operativos",
    domain:      "EFFICIENCY",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Implementación de automatización para reducir carga operativa y errores.",
    limitations: ["suggestedOnly: true", "Análisis de ROI y procesos críticos necesario"],
  },
  {
    id:          "CDC_020",
    title:       "Experiencia del cliente como ventaja competitiva",
    domain:      "MARKET",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Diferenciación basada en excelencia en experiencia del cliente.",
    limitations: ["suggestedOnly: true", "Requiere voz del cliente actual y métricas NPS"],
  },
  {
    id:          "CDC_021",
    title:       "Resiliencia ante disrupciones de mercado",
    domain:      "RISK",
    horizon:     "MEDIUM_TERM",
    status:      "UNDER_REVIEW",
    description: "Construcción de capacidades para adaptarse a cambios abruptos del entorno.",
    limitations: ["suggestedOnly: true", "Escenarios de disrupción requieren validación"],
  },
  {
    id:          "CDC_022",
    title:       "Monetización de activos digitales",
    domain:      "INNOVATION",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Generación de nuevas fuentes de ingresos a partir de datos y plataformas digitales.",
    limitations: ["suggestedOnly: true", "Modelo de negocio específico requiere definición"],
  },
  {
    id:          "CDC_023",
    title:       "Optimización del portafolio de inversiones",
    domain:      "PROFITABILITY",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Reasignación de recursos hacia iniciativas de mayor retorno estratégico.",
    limitations: ["suggestedOnly: true", "Análisis de ROI detallado por iniciativa requerido"],
  },
  {
    id:          "CDC_024",
    title:       "Cumplimiento regulatorio proactivo",
    domain:      "GOVERNANCE",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Anticipación a cambios regulatorios para minimizar riesgo de cumplimiento.",
    limitations: ["suggestedOnly: true", "Marco regulatorio local específico no incluido"],
  },
  {
    id:          "CDC_025",
    title:       "Gestión de concentración de clientes",
    domain:      "RISK",
    horizon:     "SHORT_TERM",
    status:      "MISALIGNED",
    description: "Reducción de dependencia de pocos clientes clave para mejorar resiliencia.",
    limitations: ["suggestedOnly: true", "Datos de concentración de cartera requeridos"],
  },
  {
    id:          "CDC_026",
    title:       "Plataforma de innovación interna",
    domain:      "INNOVATION",
    horizon:     "LONG_TERM",
    status:      "UNDER_REVIEW",
    description: "Creación de estructura interna para fomentar la innovación sistemática.",
    limitations: ["suggestedOnly: true", "Capacidades de innovación actuales deben evaluarse"],
  },
  {
    id:          "CDC_027",
    title:       "Segmentación y especialización comercial",
    domain:      "MARKET",
    horizon:     "SHORT_TERM",
    status:      "ALIGNED",
    description: "Foco en segmentos de alta rentabilidad con propuestas de valor diferenciadas.",
    limitations: ["suggestedOnly: true", "Análisis de segmentación con datos reales necesario"],
  },
  {
    id:          "CDC_028",
    title:       "Infraestructura de datos estratégicos",
    domain:      "TECHNOLOGY",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Desarrollo de capacidades de datos para soportar decisiones estratégicas.",
    limitations: ["suggestedOnly: true", "Estado actual de madurez de datos debe evaluarse"],
  },
  {
    id:          "CDC_029",
    title:       "Modelo operativo ágil",
    domain:      "OPERATIONS",
    horizon:     "MEDIUM_TERM",
    status:      "PARTIALLY_ALIGNED",
    description: "Adopción de metodologías ágiles para mejorar velocidad de respuesta al mercado.",
    limitations: ["suggestedOnly: true", "Transformación cultural implícita requiere gestión del cambio"],
  },
  {
    id:          "CDC_030",
    title:       "Expansión de capacidad productiva",
    domain:      "GROWTH",
    horizon:     "MEDIUM_TERM",
    status:      "UNDER_REVIEW",
    description: "Inversión en capacidad para soportar crecimiento de demanda proyectado.",
    limitations: ["suggestedOnly: true", "Proyecciones de demanda deben validarse con datos de mercado"],
  },
] as const;
