/**
 * lib/operational-map/audit/operational-kpi-registry.ts
 *
 * Operational KPI Registry — Static connection declarations.
 *
 * INTERNAL ONLY: SUPER_ADMIN / AGENTIK_ADMIN
 *
 * Declares the DESIGN INTENT (expectedSources) and ACTUAL STATE (actualSources,
 * connectionHealth) for every operational KPI in Agentik.
 *
 * System state encoded here reflects Castillitos / Agentik as of sprint
 * AGENTIK-OPERATIONAL-CONNECTION-AUDIT-01. Update as connectors are built.
 *
 * Domains covered:
 *   torre_control (14) | comercial (13) | cobranza (10) | tesoreria (9)
 *   finanzas (10) | logistica (6) | produccion (4)
 *   Total: 66 KPI entries
 *
 * Sprint: AGENTIK-OPERATIONAL-CONNECTION-AUDIT-01
 */

import type { KpiRegistryEntry } from "./operational-connection-audit-types";

// ─── Torre de Control (14 KPIs) ───────────────────────────────────────────────

const TORRE_CONTROL_KPIS: KpiRegistryEntry[] = [
  {
    domain: "torre_control", entityKey: "tasa_cobertura",
    entityLabel: "Tasa de Cobertura de Inventario",
    kpiDefinition: "% de referencias con cobertura ≥ umbral mínimo operativo",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG INVENTARIO (ODBC)", "Agentik CommercialCoverageSnapshot"],
    actualSources:   ["CommercialCoverageSnapshot (manual upload)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Tasa calculada sobre datos de carga manual, no en tiempo real.",
    recommendedAction: "Confirmar tabla SAG de inventario y construir ODBC V2 automático.",
    affectedModules: ["torre_control", "comercial", "maletas"],
  },
  {
    domain: "torre_control", entityKey: "dias_cobertura_promedio",
    entityLabel: "Días de Cobertura Promedio",
    kpiDefinition: "Días proyectados de stock disponible al ritmo de demanda actual",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG INVENTARIO", "Agentik velocidad de venta"],
    actualSources:   ["CommercialCoverageSnapshot (campo coverageDays)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "coverageDays calculado por Agentik sobre snapshot manual. No refleja SAG en tiempo real.",
    recommendedAction: "Validar velocidad de venta contra SAG FACTURAS y PEDIDOS.",
    affectedModules: ["torre_control", "comercial"],
  },
  {
    domain: "torre_control", entityKey: "cartera_vencida_total",
    entityLabel: "Cartera Vencida Total",
    kpiDefinition: "Suma de saldos vencidos de todos los clientes activos",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC — tabla CXCCXC o equivalente)"],
    actualSources:   ["SAG CARTERA adapter (ODBC parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Tabla confirmada. Campos de vencimiento y moneda aún por validar en instancia Castillitos.",
    recommendedAction: "Confirmar campos FECHA_VENCIMIENTO, SALDO_PENDIENTE con DBA SAG Castillitos.",
    affectedModules: ["torre_control", "cobranza", "finanzas"],
  },
  {
    domain: "torre_control", entityKey: "score_riesgo_mora",
    entityLabel: "Score de Riesgo de Mora",
    kpiDefinition: "Score 0–100 de riesgo de mora calculado por Agentik por cliente",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik scorer — inputs desde SAG CARTERA"],
    actualSources:   ["Agentik (partial — scorer activo, inputs SAG parciales)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Scorer activo pero inputs de SAG no validados al 100%.",
    recommendedAction: "Completar validación de campos SAG CARTERA para mejorar precisión del score.",
    affectedModules: ["torre_control", "cobranza"],
  },
  {
    domain: "torre_control", entityKey: "pedidos_pendientes_despacho",
    entityLabel: "Pedidos Pendientes de Despacho",
    kpiDefinition: "Conteo y valor de pedidos confirmados aún sin despachar",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS (ODBC)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin conexión a SAG PEDIDOS. Dato mostrado es placeholder.",
    recommendedAction: "Confirmar tabla SAG de pedidos (DOCPED, PEDIDOS o equivalente) con DBA.",
    affectedModules: ["torre_control", "logistica"],
  },
  {
    domain: "torre_control", entityKey: "ventas_dia_fuente1",
    entityLabel: "Ventas del Día (FUENTE_1)",
    kpiDefinition: "Ventas facturadas (FUENTE_1 oficial) del día actual",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG FACTURAS FUENTE_1 (ODBC — tabla FAENCFAC o equivalente)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "ODBC de facturas no construido. KPI no disponible en tiempo real.",
    recommendedAction: "Priorizar construcción ODBC V2 para FACTURAS SAG. Confirmar tabla con DBA.",
    affectedModules: ["torre_control", "finanzas", "comercial"],
  },
  {
    domain: "torre_control", entityKey: "recaudos_dia",
    entityLabel: "Recaudos del Día",
    kpiDefinition: "Suma de pagos recibidos aplicados a cartera en el día",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA — movimientos de pago del día"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "pending", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Cartera adaptada, pero campos de pagos/movimientos del día no confirmados.",
    recommendedAction: "Confirmar filtro de fecha y tipo de movimiento en SAG CARTERA.",
    affectedModules: ["torre_control", "tesoreria", "cobranza"],
  },
  {
    domain: "torre_control", entityKey: "alertas_criticas",
    entityLabel: "Alertas Activas Críticas",
    kpiDefinition: "Conteo de alertas de prioridad crítica sin resolver",
    priority: "high", frequency: "realtime", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik AlertEngine"],
    actualSources:   ["Agentik AlertEngine"],
    connectionHealth: "live", dataFreshness: "realtime", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo — sistema Agentik nativo.",
    recommendedAction: "Ninguna. Conector activo.",
    affectedModules: ["torre_control"],
  },
  {
    domain: "torre_control", entityKey: "reps_activos_hoy",
    entityLabel: "Representantes Activos Hoy",
    kpiDefinition: "Representantes con al menos una actividad registrada hoy",
    priority: "medium", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik ActivityLog"],
    actualSources:   ["Agentik ActivityLog"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo — sistema Agentik nativo.",
    recommendedAction: "Ninguna.",
    affectedModules: ["torre_control"],
  },
  {
    domain: "torre_control", entityKey: "tickets_cobranza_abiertos",
    entityLabel: "Tickets de Cobranza Abiertos",
    kpiDefinition: "Gestiones de cobranza sin resultado final registrado",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik CollectionCase"],
    actualSources:   ["Agentik CollectionCase"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo — sistema Agentik nativo.",
    recommendedAction: "Ninguna.",
    affectedModules: ["torre_control", "cobranza"],
  },
  {
    domain: "torre_control", entityKey: "despachos_transito",
    entityLabel: "Despachos en Tránsito",
    kpiDefinition: "Pedidos despachados aún no entregados ni devueltos",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG DESPACHOS / REMISIONES (ODBC)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Tabla SAG de despachos/remisiones no confirmada.",
    recommendedAction: "Confirmar tabla SAG para remisiones (FUENTE_2) con DBA.",
    affectedModules: ["torre_control", "logistica"],
  },
  {
    domain: "torre_control", entityKey: "score_salud_inventario",
    entityLabel: "Score de Salud de Inventario",
    kpiDefinition: "Score 0–100 de salud del inventario (cobertura + quiebre + demanda)",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik scorer — inputs CommercialCoverageSnapshot"],
    actualSources:   ["Agentik CommercialCoverageSnapshot (manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Score calculado sobre snapshot manual. No refleja cambios de inventario intradiario.",
    recommendedAction: "Automatizar sync SAG→CommercialCoverageSnapshot.",
    affectedModules: ["torre_control", "comercial"],
  },
  {
    domain: "torre_control", entityKey: "liquidez_operativa_dia",
    entityLabel: "Liquidez Operativa del Día",
    kpiDefinition: "Saldo disponible en cuentas bancarias + recaudos del día",
    priority: "critical", frequency: "daily", sourceOfTruth: "Banco",
    expectedSources: ["Conector bancario (Open Banking o extracto)"],
    actualSources:   [],
    connectionHealth: "disconnected", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin conector bancario. Liquidez no visible en Agentik.",
    recommendedAction: "Integrar extracto bancario (API bancaria o carga manual diaria).",
    affectedModules: ["torre_control", "tesoreria", "finanzas"],
  },
  {
    domain: "torre_control", entityKey: "nps_operacional",
    entityLabel: "NPS Operacional",
    kpiDefinition: "Net Promoter Score operacional de clientes activos",
    priority: "low", frequency: "weekly", sourceOfTruth: "CRM",
    expectedSources: ["CRM (futuro)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "CRM no integrado. KPI no disponible.",
    recommendedAction: "Integrar CRM en sprint futuro.",
    affectedModules: ["torre_control"],
  },
];

// ─── Pedidos del Día KPIs (Torre de Control + Comercial) ─────────────────────
// Canonical "Pedidos del Día" family. Distinct from "Pedidos Pendientes de
// Despacho" (already in registry). These track orders CREATED today by channel.

const PEDIDOS_DIA_KPIS: KpiRegistryEntry[] = [
  {
    domain: "torre_control", entityKey: "pedidos_dia",
    entityLabel: "Pedidos del Día",
    kpiDefinition: "Cantidad y valor de pedidos creados durante el día operativo, separados por canal, vendedor, estado y sincronización SAG.",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: [
      "SAG PEDIDOS / PD (ODBC — tabla DOCPED o equivalente)",
      "CRM AOS_Quotes / Opportunities",
      "Agentik OperationalOrders",
    ],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "KPI crítico sin fuente activa. Torre de Control no puede calcular pipeline diario.",
    recommendedAction: "Confirmar tabla SAG PEDIDOS (DOCPED o PD) con DBA. Cruzar con CRM AOS_Quotes.",
    affectedModules: ["torre_control", "comercial", "logistica"],
  },
  {
    domain: "comercial", entityKey: "pedidos_dia_crm",
    entityLabel: "Pedidos del Día — CRM",
    kpiDefinition: "Pedidos / cotizaciones creadas hoy en el CRM por vendedor y estado de aprobación.",
    priority: "high", frequency: "daily", sourceOfTruth: "CRM",
    expectedSources: ["CRM AOS_Quotes", "CRM Opportunities"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "CRM no integrado. Pedidos CRM no visibles en Agentik.",
    recommendedAction: "Integrar módulo AOS_Quotes del CRM vía API o conector.",
    affectedModules: ["comercial"],
  },
  {
    domain: "comercial", entityKey: "pedidos_dia_sag",
    entityLabel: "Pedidos del Día — SAG PD",
    kpiDefinition: "Pedidos ingresados hoy en SAG (módulo PD). Incluye todos los estados: aprobado, pendiente, retenido, rechazado.",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS / PD (ODBC — tabla DOCPED o equivalente)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Tabla SAG PEDIDOS no confirmada. Sin visibilidad de pedidos SAG del día.",
    recommendedAction: "Confirmar tabla DOCPED o PD con DBA SAG Castillitos.",
    affectedModules: ["comercial", "logistica"],
  },
  {
    domain: "comercial", entityKey: "pedidos_dia_consolidado",
    entityLabel: "Pedidos del Día — Consolidado",
    kpiDefinition: "Suma de pedidos del día consolidados desde CRM + SAG PD + Agentik, deduplicados por referencia cruzada.",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik OperationalOrders", "SAG PEDIDOS", "CRM AOS_Quotes"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Consolidado requiere reconciliación CRM↔SAG. Sin fuentes activas.",
    recommendedAction: "Implementar después de conectar SAG PEDIDOS y CRM individualmente.",
    affectedModules: ["torre_control", "comercial"],
  },
  {
    domain: "comercial", entityKey: "pedidos_pendientes_sync_sag",
    entityLabel: "Pedidos Pendientes de Sincronizar SAG",
    kpiDefinition: "Pedidos creados en CRM o Agentik que aún no han sido confirmados ni creados en SAG.",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik OperationalOrders (campo sagSyncStatus)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Pedidos no sincronizados a SAG pueden generar inconsistencias de facturación.",
    recommendedAction: "Implementar campo sagSyncStatus en OperationalOrders y exponer en Torre de Control.",
    affectedModules: ["comercial", "logistica", "torre_control"],
  },
  {
    domain: "comercial", entityKey: "pedidos_rechazados_sag",
    entityLabel: "Pedidos Rechazados por SAG",
    kpiDefinition: "Pedidos que SAG rechazó por cartera, inventario, crédito u otras validaciones ERP.",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS — estado RECHAZADO / RETENIDO", "Agentik OperationalOrders"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin visibilidad de rechazos SAG. Torre de Control no puede alertar.",
    recommendedAction: "Confirmar campo de estado de pedido en SAG y filtrar por RECHAZADO/RETENIDO.",
    affectedModules: ["comercial", "cobranza", "logistica"],
  },
  {
    domain: "comercial", entityKey: "pedidos_retenidos_inventario",
    entityLabel: "Pedidos Retenidos por Inventario",
    kpiDefinition: "Pedidos que no pudieron despacharse por insuficiencia de stock en bodega.",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS — estado RETENIDO POR INVENTARIO", "Agentik OperationalReservations"],
    actualSources:   ["Agentik OperationalReservations (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Reservas Agentik activas pero sin cruce con estado real SAG PEDIDOS.",
    recommendedAction: "Cruzar OperationalReservations con estado SAG PEDIDOS para confirmar retención.",
    affectedModules: ["comercial", "logistica", "torre_control"],
  },
  {
    domain: "comercial", entityKey: "pedidos_retenidos_cartera",
    entityLabel: "Pedidos Retenidos por Cartera",
    kpiDefinition: "Pedidos bloqueados por límite de crédito o cartera vencida del cliente.",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS — estado RETENIDO CARTERA", "SAG CARTERA"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin visibilidad de retenciones por cartera. Ventas perdidas sin alertas.",
    recommendedAction: "Confirmar campo de bloqueo por cartera en SAG PEDIDOS con DBA.",
    affectedModules: ["comercial", "cobranza", "torre_control"],
  },
];

// ─── Comercial (13 KPIs) ──────────────────────────────────────────────────────

const COMERCIAL_KPIS: KpiRegistryEntry[] = [
  {
    domain: "comercial", entityKey: "catalogo_activo",
    entityLabel: "Catálogo de Referencias Activas",
    kpiDefinition: "Total de SKUs activos con descripción, línea y estado",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG ARTICULOS (ODBC)"],
    actualSources:   ["CommercialCoverageSnapshot (campo description, refCode)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Catálogo viene de carga manual. Nuevas referencias no aparecen automáticamente.",
    recommendedAction: "Confirmar tabla SAG ARTICULOS y construir sincronización automática.",
    affectedModules: ["comercial", "maletas", "marketing_studio"],
  },
  {
    domain: "comercial", entityKey: "disponibilidad_ref",
    entityLabel: "Disponibilidad Operacional por Referencia",
    kpiDefinition: "operationalAvailableQty = physicalQty − reservedQty − salesAssigned − pendingTransfers",
    priority: "critical", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik OperationalInventoryItem (fórmula propia)"],
    actualSources:   ["Agentik OperationalInventoryItem"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Fórmula Agentik activa. Inputs de SAG disponible marcados como no confiables.",
    recommendedAction: "Mantener fórmula propia. Validar inputs físicos con DBA SAG.",
    affectedModules: ["comercial", "maletas"],
  },
  {
    domain: "comercial", entityKey: "precio_lista",
    entityLabel: "Precio de Lista Vigente",
    kpiDefinition: "Precio base de lista por referencia, vigente hoy",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG LISTAS_PRECIOS (ODBC — tabla por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Precios no disponibles en Agentik. Se usa precio de referencia manual.",
    recommendedAction: "Confirmar tabla SAG de listas de precios con DBA. Construir ODBC.",
    affectedModules: ["comercial", "maletas"],
  },
  {
    domain: "comercial", entityKey: "score_demanda",
    entityLabel: "Score de Demanda por Referencia",
    kpiDefinition: "Score 0–100 de presión de demanda calculado por Agentik",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik scorer — inputs CommercialCoverageSnapshot"],
    actualSources:   ["CommercialCoverageSnapshot (campo demandPressureScore)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Score calculado sobre datos manuales. No refleja demanda en tiempo real.",
    recommendedAction: "Automatizar fuente SAG para mejorar precisión.",
    affectedModules: ["comercial", "maletas", "torre_control"],
  },
  {
    domain: "comercial", entityKey: "cartera_cliente",
    entityLabel: "Cartera del Cliente",
    kpiDefinition: "Saldo total de cartera del cliente (vencida + vigente)",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Tabla conectada. Campos de saldo por cliente no completamente validados.",
    recommendedAction: "Confirmar campo SALDO_CLIENTE y filtro por NIT/código con DBA.",
    affectedModules: ["comercial", "cobranza"],
  },
  {
    domain: "comercial", entityKey: "historial_pedidos",
    entityLabel: "Historial de Pedidos del Cliente",
    kpiDefinition: "Últimos N pedidos del cliente con estado y valor",
    priority: "high", frequency: "on_demand", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS (ODBC — tabla por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a historial de pedidos SAG. Representante no puede ver historial.",
    recommendedAction: "Confirmar tabla SAG de pedidos con DBA y construir query.",
    affectedModules: ["comercial"],
  },
  {
    domain: "comercial", entityKey: "politica_credito",
    entityLabel: "Política de Crédito Vigente",
    kpiDefinition: "Cupo de crédito, plazo, condiciones actuales del cliente",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG TERCEROS — campos de crédito (por confirmar)"],
    actualSources:   ["SAG TERCEROS adapter (campos básicos)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "TERCEROS conectado pero campos de crédito (cupo, plazo) no confirmados.",
    recommendedAction: "Confirmar campos de crédito en SAG TERCEROS con DBA.",
    affectedModules: ["comercial", "cobranza"],
  },
  {
    domain: "comercial", entityKey: "ultima_visita_rep",
    entityLabel: "Última Visita del Representante",
    kpiDefinition: "Fecha y resultado de la última visita comercial registrada",
    priority: "medium", frequency: "event_driven", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik ActivityLog"],
    actualSources:   ["Agentik ActivityLog"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo — sistema Agentik nativo.",
    recommendedAction: "Ninguna.",
    affectedModules: ["comercial"],
  },
  {
    domain: "comercial", entityKey: "pedido_en_curso",
    entityLabel: "Pedido en Curso",
    kpiDefinition: "Pedido activo del cliente en proceso de aprobación o despacho",
    priority: "high", frequency: "realtime", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS (ODBC)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a pedidos en curso SAG. Representante no puede verificar estado.",
    recommendedAction: "Confirmar tabla SAG PEDIDOS y construir query de estado activo.",
    affectedModules: ["comercial"],
  },
  {
    domain: "comercial", entityKey: "cobertura_ref",
    entityLabel: "Cobertura Estimada por Referencia",
    kpiDefinition: "Días estimados de stock disponible por SKU",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["CommercialCoverageSnapshot (campo coverageDays)"],
    actualSources:   ["CommercialCoverageSnapshot (manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Datos manuales. Cobertura puede estar desactualizada.",
    recommendedAction: "Automatizar sync inventario SAG.",
    affectedModules: ["comercial", "maletas"],
  },
  {
    domain: "comercial", entityKey: "velocidad_venta",
    entityLabel: "Velocidad de Venta por Referencia",
    kpiDefinition: "Unidades vendidas por día (promedio móvil 30d)",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG FACTURAS (ODBC)", "Agentik scorer"],
    actualSources:   ["CommercialCoverageSnapshot (campo dailyVelocity — manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "low",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Velocidad calculada sobre datos manuales. Derivada de snapshot, no de facturas reales.",
    recommendedAction: "Construir ODBC de facturas SAG para calcular velocidad real.",
    affectedModules: ["comercial", "torre_control", "maletas"],
  },
  {
    domain: "comercial", entityKey: "presion_demanda",
    entityLabel: "Presión de Demanda",
    kpiDefinition: "Ratio pedidos pendientes / disponible por referencia",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik — inputs CommercialCoverageSnapshot"],
    actualSources:   ["CommercialCoverageSnapshot (campo demandPressureScore — manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Score calculado sobre snapshot manual.",
    recommendedAction: "Automatizar fuente SAG para presión de demanda real.",
    affectedModules: ["comercial", "maletas"],
  },
  {
    domain: "comercial", entityKey: "score_cobertura",
    entityLabel: "Score de Cobertura Operacional",
    kpiDefinition: "Score 0–100 de cobertura del portafolio (Agentik operationalScore)",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik CommercialCoverageSnapshot (campo operationalScore)"],
    actualSources:   ["CommercialCoverageSnapshot (manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "medium",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Score sobre datos manuales.",
    recommendedAction: "Automatizar sync SAG→CommercialCoverageSnapshot.",
    affectedModules: ["comercial", "maletas", "torre_control"],
  },
];

// ─── Cobranza (10 KPIs) ───────────────────────────────────────────────────────

const COBRANZA_KPIS: KpiRegistryEntry[] = [
  {
    domain: "cobranza", entityKey: "saldo_vencido_cliente",
    entityLabel: "Saldo Vencido por Cliente",
    kpiDefinition: "Suma de facturas vencidas por NIT de cliente",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Tabla conectada pero campos de vencimiento por confirmar.",
    recommendedAction: "Confirmar campos FECHA_VENCIMIENTO, SALDO_VENCIDO con DBA SAG.",
    affectedModules: ["cobranza", "torre_control"],
  },
  {
    domain: "cobranza", entityKey: "dias_mora_promedio",
    entityLabel: "Días de Mora Promedio",
    kpiDefinition: "Promedio ponderado de días vencidos de la cartera activa",
    priority: "critical", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik scorer — inputs SAG CARTERA"],
    actualSources:   ["Agentik scorer (inputs parciales SAG)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Cálculo parcialmente correcto. Depende de campos SAG no confirmados.",
    recommendedAction: "Completar validación SAG CARTERA para mejorar precisión.",
    affectedModules: ["cobranza", "torre_control"],
  },
  {
    domain: "cobranza", entityKey: "documentos_vencidos",
    entityLabel: "Documentos Vencidos",
    kpiDefinition: "Conteo y lista de facturas vencidas pendientes de pago",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Tabla confirmada. Filtro de vencimiento por validar.",
    recommendedAction: "Confirmar lógica de vencimiento SAG (campo vs fecha sistema).",
    affectedModules: ["cobranza"],
  },
  {
    domain: "cobranza", entityKey: "historial_pagos",
    entityLabel: "Historial de Pagos del Cliente",
    kpiDefinition: "Pagos aplicados en los últimos 90 días por cliente",
    priority: "high", frequency: "on_demand", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA — movimientos de recibo (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "pending", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Historial de pagos no disponible. Bloquea análisis de comportamiento.",
    recommendedAction: "Confirmar tabla/vista SAG de movimientos de cartera con DBA.",
    affectedModules: ["cobranza"],
  },
  {
    domain: "cobranza", entityKey: "score_riesgo_cobranza",
    entityLabel: "Score de Riesgo de Mora",
    kpiDefinition: "Score 0–100 de riesgo de incumplimiento para el período",
    priority: "critical", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik scoring engine"],
    actualSources:   ["Agentik scoring engine (inputs parciales)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Scorer activo pero alimentado por datos parciales de SAG.",
    recommendedAction: "Mejorar cobertura de inputs SAG para el scorer.",
    affectedModules: ["cobranza", "torre_control"],
  },
  {
    domain: "cobranza", entityKey: "promesas_pago_activas",
    entityLabel: "Promesas de Pago Activas",
    kpiDefinition: "Compromisos de pago registrados por gestores, por vencer",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik CollectionCase — campo promise_date"],
    actualSources:   ["Agentik CollectionCase"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo — sistema Agentik nativo.",
    recommendedAction: "Ninguna.",
    affectedModules: ["cobranza"],
  },
  {
    domain: "cobranza", entityKey: "visitas_registradas_hoy",
    entityLabel: "Visitas Registradas Hoy",
    kpiDefinition: "Gestiones de cobranza completadas con resultado registrado en el día",
    priority: "high", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik ActivityLog"],
    actualSources:   ["Agentik ActivityLog"],
    connectionHealth: "live", dataFreshness: "today", confidenceLevel: "high",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin riesgo.",
    recommendedAction: "Ninguna.",
    affectedModules: ["cobranza"],
  },
  {
    domain: "cobranza", entityKey: "tasa_recuperacion",
    entityLabel: "Tasa de Recuperación del Período",
    kpiDefinition: "% de cartera vencida recuperada en el período actual",
    priority: "high", frequency: "weekly", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG CARTERA (recaudos)", "Agentik ActivityLog"],
    actualSources:   ["SAG CARTERA adapter (parcial)", "Agentik ActivityLog"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Tasa calculada parcialmente. Campos de recaudos SAG no confirmados.",
    recommendedAction: "Confirmar campos de pago/recaudo en SAG CARTERA.",
    affectedModules: ["cobranza", "finanzas"],
  },
  {
    domain: "cobranza", entityKey: "documentos_proximos_vencer",
    entityLabel: "Documentos Próximos a Vencer (7 días)",
    kpiDefinition: "Facturas que vencen en los próximos 7 días",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Depende de lógica de fecha vencimiento SAG no confirmada.",
    recommendedAction: "Confirmar campo FECHA_VENCIMIENTO y lógica de cálculo.",
    affectedModules: ["cobranza"],
  },
  {
    domain: "cobranza", entityKey: "cupo_credito_restante",
    entityLabel: "Cupo de Crédito Restante",
    kpiDefinition: "Diferencia entre cupo aprobado y saldo total pendiente",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG TERCEROS — campo cupo (por confirmar)"],
    actualSources:   ["SAG TERCEROS adapter (campos básicos)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Campo cupo de crédito no confirmado en SAG TERCEROS Castillitos.",
    recommendedAction: "Confirmar campo cupo/línea de crédito en SAG TERCEROS con DBA.",
    affectedModules: ["cobranza", "comercial"],
  },
];

// ─── Tesorería (9 KPIs) ───────────────────────────────────────────────────────

const TESORERIA_KPIS: KpiRegistryEntry[] = [
  {
    domain: "tesoreria", entityKey: "saldo_cuentas_bancarias",
    entityLabel: "Saldo en Cuentas Bancarias",
    kpiDefinition: "Saldo disponible en cuentas bancarias de la empresa",
    priority: "critical", frequency: "daily", sourceOfTruth: "Banco",
    expectedSources: ["Conector bancario (API o extracto)"],
    actualSources:   [],
    connectionHealth: "disconnected", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin conector bancario. Tesorería opera sin visibilidad de saldo real.",
    recommendedAction: "Integrar API bancaria o carga manual de extracto diario.",
    affectedModules: ["tesoreria", "torre_control", "finanzas"],
  },
  {
    domain: "tesoreria", entityKey: "recaudos_dia_tesoreria",
    entityLabel: "Recaudos del Día (Tesorería)",
    kpiDefinition: "Ingresos de caja registrados hoy (pagos aplicados a cartera)",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA — movimientos de recaudo"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "low",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Parcialmente conectado. Campos de recaudo sin confirmar.",
    recommendedAction: "Confirmar campos de recaudo y banco destino en SAG CARTERA.",
    affectedModules: ["tesoreria", "torre_control"],
  },
  {
    domain: "tesoreria", entityKey: "disponible_banco_hoy",
    entityLabel: "Disponible en Banco Hoy",
    kpiDefinition: "Saldo disponible para operaciones del día",
    priority: "critical", frequency: "daily", sourceOfTruth: "Banco",
    expectedSources: ["Conector bancario"],
    actualSources:   [],
    connectionHealth: "disconnected", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin conector bancario. Disponibilidad diaria desconocida.",
    recommendedAction: "Integrar extracto bancario.",
    affectedModules: ["tesoreria"],
  },
  {
    domain: "tesoreria", entityKey: "pagos_programados_7d",
    entityLabel: "Pagos Programados Próximos 7 Días",
    kpiDefinition: "Compromisos de pago a proveedores o nómina en los próximos 7 días",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PROVEEDORES / CUENTAS POR PAGAR (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a cuentas por pagar SAG.",
    recommendedAction: "Confirmar tabla SAG de cuentas por pagar con DBA.",
    affectedModules: ["tesoreria", "finanzas"],
  },
  {
    domain: "tesoreria", entityKey: "flujo_caja_30d",
    entityLabel: "Flujo de Caja Proyectado 30 Días",
    kpiDefinition: "Proyección de ingresos − egresos para los próximos 30 días",
    priority: "high", frequency: "weekly", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik planner — inputs SAG CARTERA + SAG PAGOS + Banco"],
    actualSources:   ["Agentik planner (sin inputs bancarios, SAG parcial)"],
    connectionHealth: "mock", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Proyección calculada sobre datos incompletos. Resultado no confiable.",
    recommendedAction: "Esperar conexión bancaria y validación SAG para activar este KPI.",
    affectedModules: ["tesoreria", "finanzas"],
  },
  {
    domain: "tesoreria", entityKey: "cartera_cobrar_entradas",
    entityLabel: "Cartera por Cobrar (entradas esperadas)",
    kpiDefinition: "Total de cartera vigente próxima a vencer = entradas de efectivo esperadas",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "Parcialmente conectado. Proyección de vencimientos pendiente de validar.",
    recommendedAction: "Confirmar lógica de vencimiento SAG CARTERA.",
    affectedModules: ["tesoreria", "cobranza"],
  },
  {
    domain: "tesoreria", entityKey: "obligaciones_financieras",
    entityLabel: "Obligaciones Financieras Vigentes",
    kpiDefinition: "Créditos bancarios, leasing y obligaciones activas",
    priority: "high", frequency: "monthly", sourceOfTruth: "Banco",
    expectedSources: ["Banco / SAG contabilidad (por confirmar)"],
    actualSources:   [],
    connectionHealth: "disconnected", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a obligaciones financieras.",
    recommendedAction: "Evaluar si SAG contabilidad registra esto o requiere fuente externa.",
    affectedModules: ["tesoreria", "finanzas"],
  },
  {
    domain: "tesoreria", entityKey: "conciliacion_bancaria_pendiente",
    entityLabel: "Conciliación Bancaria Pendiente",
    kpiDefinition: "Movimientos bancarios sin conciliar contra registros SAG",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["Banco (extracto)", "SAG CARTERA / CONTABILIDAD"],
    actualSources:   ["Agentik reconciliation (módulo parcial — banco desconectado)"],
    connectionHealth: "partial", dataFreshness: "unknown", confidenceLevel: "low",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Módulo de reconciliación activo pero lado bancario desconectado.",
    recommendedAction: "Integrar extracto bancario para completar conciliación.",
    affectedModules: ["tesoreria", "finanzas"],
  },
  {
    domain: "tesoreria", entityKey: "posicion_neta_liquidez",
    entityLabel: "Posición Neta de Liquidez",
    kpiDefinition: "Banco disponible + cartera próxima − pagos programados",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["Banco", "SAG CARTERA", "SAG PAGOS"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "mock", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin banco conectado. Posición neta es estimado no confiable.",
    recommendedAction: "Bloquear display de este KPI hasta conectar banco.",
    affectedModules: ["tesoreria", "finanzas", "torre_control"],
  },
];

// ─── Finanzas (10 KPIs) ───────────────────────────────────────────────────────

const FINANZAS_KPIS: KpiRegistryEntry[] = [
  {
    domain: "finanzas", entityKey: "ventas_brutas_fuente1",
    entityLabel: "Ventas Brutas del Período (FUENTE_1)",
    kpiDefinition: "Suma de facturas FUENTE_1 (DIAN) emitidas en el período",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG FACTURAS FUENTE_1 (ODBC — tabla FAENCFAC o equivalente)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "ODBC de facturas no construido. Ventas no disponibles en Agentik.",
    recommendedAction: "PRIORITARIO: confirmar tabla SAG facturas y construir ODBC V2.",
    affectedModules: ["finanzas", "torre_control"],
  },
  {
    domain: "finanzas", entityKey: "costo_ventas",
    entityLabel: "Costo de Ventas",
    kpiDefinition: "Costo reconocido en ventas facturadas del período",
    priority: "high", frequency: "monthly", sourceOfTruth: "SAG",
    expectedSources: ["SAG CONTABILIDAD / INVENTARIOS (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a costo de ventas SAG.",
    recommendedAction: "Confirmar si SAG PYA tiene costo de ventas en contabilidad o inventarios.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "margen_bruto",
    entityLabel: "Margen Bruto",
    kpiDefinition: "(Ventas brutas − Costo de ventas) / Ventas brutas",
    priority: "high", frequency: "monthly", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik — inputs ventas_brutas + costo_ventas"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Depende de ventas y costos SAG no conectados.",
    recommendedAction: "Esperar conexión de ventas brutas y costo SAG.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "ventas_netas",
    entityLabel: "Ventas Netas (post-devoluciones)",
    kpiDefinition: "Ventas brutas menos notas crédito y devoluciones",
    priority: "high", frequency: "monthly", sourceOfTruth: "SAG",
    expectedSources: ["SAG FACTURAS + NOTAS CRÉDITO (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a notas crédito SAG.",
    recommendedAction: "Confirmar tabla de notas crédito SAG con DBA.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "cartera_reconocida",
    entityLabel: "Cartera Total Reconocida (AR)",
    kpiDefinition: "Cuentas por cobrar totales reconocidas en contabilidad",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG CARTERA (ODBC)"],
    actualSources:   ["SAG CARTERA adapter (parcial)"],
    connectionHealth: "partial", dataFreshness: "today", confidenceLevel: "medium",
    sagQueryStatus: "confirmed", sagTableConfirmed: true, sagFieldsConfirmed: false,
    riskDescription: "AR parcialmente conectado. Campos contables no confirmados.",
    recommendedAction: "Confirmar totales AR vs cartera CARTERA vs libro mayor SAG.",
    affectedModules: ["finanzas", "cobranza"],
  },
  {
    domain: "finanzas", entityKey: "ingresos_diferidos",
    entityLabel: "Ingresos Diferidos (FUENTE_2 pendiente conversión)",
    kpiDefinition: "Valor de remisiones FUENTE_2 no convertidas a factura FUENTE_1",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG REMISIONES FUENTE_2 (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Ingresos diferidos FUENTE_2 no visibles. Impacto en cierre contable.",
    recommendedAction: "Confirmar tabla SAG de remisiones y lógica FUENTE_2 con DBA.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "gastos_operativos",
    entityLabel: "Gastos Operativos del Período",
    kpiDefinition: "Gastos causados en el período (nómina, servicios, etc.)",
    priority: "medium", frequency: "monthly", sourceOfTruth: "SAG",
    expectedSources: ["SAG CONTABILIDAD (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Gastos no visibles en Agentik.",
    recommendedAction: "Confirmar plan de cuentas de gastos SAG con DBA.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "ebitda_estimado",
    entityLabel: "EBITDA Estimado",
    kpiDefinition: "Utilidad operativa antes de intereses, impuestos, depreciación y amortización",
    priority: "medium", frequency: "monthly", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik — inputs ventas_netas + costos + gastos"],
    actualSources:   [],
    connectionHealth: "mock", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin inputs reales. EBITDA es placeholder no confiable.",
    recommendedAction: "Esperar conexión completa de ingresos y costos SAG.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "cierre_mensual",
    entityLabel: "Indicadores de Cierre Mensual",
    kpiDefinition: "Estado de cierre contable: documentos, conciliación, aprobación",
    priority: "high", frequency: "monthly", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG CONTABILIDAD", "Agentik reconciliation"],
    actualSources:   ["Agentik reconciliation (módulo activo — SAG parcial)"],
    connectionHealth: "partial", dataFreshness: "unknown", confidenceLevel: "low",
    sagQueryStatus: "pending", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Módulo de cierre activo pero inputs SAG contabilidad no conectados.",
    recommendedAction: "Conectar SAG contabilidad para completar cierre en Agentik.",
    affectedModules: ["finanzas"],
  },
  {
    domain: "finanzas", entityKey: "documentos_dian",
    entityLabel: "Balance de Documentos DIAN",
    kpiDefinition: "Facturas electrónicas DIAN emitidas vs rechazadas vs aceptadas",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG DIAN / facturación electrónica (por confirmar)"],
    actualSources:   [],
    connectionHealth: "disconnected", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a estado DIAN. Riesgo de compliance no visible.",
    recommendedAction: "Confirmar si SAG expone estado DIAN por API o tabla interna.",
    affectedModules: ["finanzas"],
  },
];

// ─── Logística (6 KPIs) ───────────────────────────────────────────────────────

const LOGISTICA_KPIS: KpiRegistryEntry[] = [
  {
    domain: "logistica", entityKey: "pedidos_pendientes_despacho",
    entityLabel: "Pedidos Pendientes de Despacho",
    kpiDefinition: "Pedidos aprobados listos para despachar",
    priority: "critical", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PEDIDOS (ODBC)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a SAG PEDIDOS. Logística ciega en Agentik.",
    recommendedAction: "Confirmar tabla SAG de pedidos con DBA. Prioridad alta.",
    affectedModules: ["logistica", "torre_control"],
  },
  {
    domain: "logistica", entityKey: "despachos_en_transito",
    entityLabel: "Despachos en Tránsito",
    kpiDefinition: "Remisiones FUENTE_2 emitidas, no entregadas ni devueltas",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG REMISIONES FUENTE_2 (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Remisiones no disponibles en Agentik.",
    recommendedAction: "Confirmar tabla SAG para remisiones (FUENTE_2) con DBA.",
    affectedModules: ["logistica", "torre_control"],
  },
  {
    domain: "logistica", entityKey: "entregas_completadas_hoy",
    entityLabel: "Entregas Completadas Hoy",
    kpiDefinition: "Pedidos con entrega confirmada en el día",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG DESPACHOS — estado entregado (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin acceso a confirmación de entrega SAG.",
    recommendedAction: "Confirmar cómo SAG marca entrega confirmada (campo estado).",
    affectedModules: ["logistica"],
  },
  {
    domain: "logistica", entityKey: "tiempo_promedio_entrega",
    entityLabel: "Tiempo Promedio de Entrega",
    kpiDefinition: "Promedio de días entre despacho y entrega confirmada",
    priority: "medium", frequency: "weekly", sourceOfTruth: "SAG+Agentik",
    expectedSources: ["SAG DESPACHOS (fecha despacho)", "SAG/campo confirmación entrega"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin datos de logística SAG. KPI no calculable.",
    recommendedAction: "Esperar conexión SAG PEDIDOS y DESPACHOS.",
    affectedModules: ["logistica"],
  },
  {
    domain: "logistica", entityKey: "devoluciones_activas",
    entityLabel: "Devoluciones Activas",
    kpiDefinition: "Pedidos con devolución iniciada, en proceso o pendiente de crédito",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG DEVOLUCIONES / NOTAS DÉBITO (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Devoluciones no visibles en Agentik.",
    recommendedAction: "Confirmar tabla/proceso SAG de devoluciones con DBA.",
    affectedModules: ["logistica", "finanzas"],
  },
  {
    domain: "logistica", entityKey: "capacidad_despacho",
    entityLabel: "Capacidad de Despacho Disponible",
    kpiDefinition: "% de capacidad de despacho utilizada vs disponible hoy",
    priority: "medium", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik (entrada manual de capacidad)"],
    actualSources:   ["Agentik (campo manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "low",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Capacidad ingresada manualmente. No refleja estado real de bodega.",
    recommendedAction: "Considerar integración con sistema de bodega o entrada periódica.",
    affectedModules: ["logistica"],
  },
];

// ─── Producción (4 KPIs) ──────────────────────────────────────────────────────

const PRODUCCION_KPIS: KpiRegistryEntry[] = [
  {
    domain: "produccion", entityKey: "ordenes_produccion_activas",
    entityLabel: "Órdenes de Producción Activas",
    kpiDefinition: "Órdenes de producción abiertas con fecha estimada",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PRODUCCIÓN (ODBC — tabla por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Producción no visible en Agentik.",
    recommendedAction: "Confirmar si SAG PYA Castillitos tiene módulo de producción activo.",
    affectedModules: ["produccion"],
  },
  {
    domain: "produccion", entityKey: "materias_primas_stock",
    entityLabel: "Materias Primas en Stock",
    kpiDefinition: "Disponibilidad de materias primas para producción planificada",
    priority: "high", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG INVENTARIO (bodega materias primas, por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Sin visibilidad de materias primas en Agentik.",
    recommendedAction: "Confirmar bodegas/tipos de artículo SAG para materias primas.",
    affectedModules: ["produccion", "inventario"],
  },
  {
    domain: "produccion", entityKey: "productos_en_proceso",
    entityLabel: "Productos en Proceso",
    kpiDefinition: "WIP — productos en línea de producción aún no terminados",
    priority: "medium", frequency: "daily", sourceOfTruth: "SAG",
    expectedSources: ["SAG PRODUCCIÓN — WIP (por confirmar)"],
    actualSources:   [],
    connectionHealth: "pending", dataFreshness: "unknown", confidenceLevel: "none",
    sagQueryStatus: "placeholder", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "WIP no visible en Agentik.",
    recommendedAction: "Confirmar si SAG PYA registra WIP o solo producto terminado.",
    affectedModules: ["produccion"],
  },
  {
    domain: "produccion", entityKey: "capacidad_produccion_utilizada",
    entityLabel: "Capacidad de Producción Utilizada",
    kpiDefinition: "% de capacidad instalada de producción en uso hoy",
    priority: "medium", frequency: "daily", sourceOfTruth: "Agentik",
    expectedSources: ["Agentik (entrada manual)"],
    actualSources:   ["Agentik (campo manual)"],
    connectionHealth: "manual", dataFreshness: "unknown", confidenceLevel: "low",
    sagQueryStatus: "not_applicable", sagTableConfirmed: false, sagFieldsConfirmed: false,
    riskDescription: "Capacidad ingresada manualmente.",
    recommendedAction: "Evaluar fuente SAG o IoT para datos de producción en tiempo real.",
    affectedModules: ["produccion"],
  },
];

// ─── Registry export ──────────────────────────────────────────────────────────

export const OPERATIONAL_KPI_REGISTRY: KpiRegistryEntry[] = [
  ...TORRE_CONTROL_KPIS,
  ...PEDIDOS_DIA_KPIS,
  ...COMERCIAL_KPIS,
  ...COBRANZA_KPIS,
  ...TESORERIA_KPIS,
  ...FINANZAS_KPIS,
  ...LOGISTICA_KPIS,
  ...PRODUCCION_KPIS,
];

export function getKpisByDomain(domain: string): KpiRegistryEntry[] {
  return OPERATIONAL_KPI_REGISTRY.filter(k => k.domain === domain);
}

export function getKpisByHealth(health: string): KpiRegistryEntry[] {
  return OPERATIONAL_KPI_REGISTRY.filter(k => k.connectionHealth === health);
}

export function getCriticalKpis(): KpiRegistryEntry[] {
  return OPERATIONAL_KPI_REGISTRY.filter(k => k.priority === "critical");
}
