/**
 * business-entity-alerts.ts
 *
 * BUSINESS-ENTITIES-CORE-01
 * Common alert model for all Digital Business Entities.
 *
 * Alerts describe conditions. They do NOT execute actions.
 * Actions are the responsibility of the Action Engine.
 *
 * No Prisma. No React. Pure domain types.
 */

import type { BusinessEntityType } from "./business-entity-types";
import type { BusinessEntitySeverity } from "./business-entity-state";

// ── Alert Category ───────────────────────────────────────────────────────────

/** Business domain categories for alerts. */
export type AlertCategory =
  | "inventory"
  | "production"
  | "commercial"
  | "financial"
  | "sync"
  | "customer"
  | "vendor"
  | "portfolio"
  | "store"
  | "order"
  | "system";

// ── Alert Action ─────────────────────────────────────────────────────────────

/** A suggested action to resolve this alert (informational only). */
export interface AlertAction {
  /** Human-readable action label. */
  label: string;
  /** Action type identifier for future Action Engine integration. */
  actionType: string;
  /** Configuration for the action (passed to Action Engine when implemented). */
  config: Record<string, unknown>;
}

// ── Business Entity Alert ────────────────────────────────────────────────────

/**
 * A condition affecting a business entity that requires attention.
 *
 * Alerts are generated by domain engines (vendor-alerts, inventory-alerts, etc.)
 * and consumed by dashboards, copilots, and future Rule Engine.
 *
 * Alerts NEVER execute actions. They only describe conditions.
 */
export interface BusinessEntityAlert {
  /** Unique alert ID. */
  id: string;
  /** The entity this alert belongs to. */
  entityId: string;
  /** Entity type. */
  entityType: BusinessEntityType;
  /** Business domain category. */
  category: AlertCategory;
  /** Severity level. */
  severity: BusinessEntitySeverity;
  /** Short title (suitable for list views). */
  title: string;
  /** Detailed description. */
  description: string;
  /** Source engine that generated this alert. */
  source: string;
  /** Priority for ordering (lower = higher priority). */
  priority: number;
  /** Suggested action to resolve (informational only). */
  action: AlertAction | null;
  /** IDs of related entities affected by this alert. */
  relatedEntityIds: string[];
  /** ISO timestamp when the alert was generated. */
  createdAt: string;
  /** ISO timestamp when the alert expires (null = no expiry). */
  expiresAt: string | null;
  /** Whether the alert has been acknowledged by an operator. */
  acknowledged: boolean;
  /** Arbitrary domain-specific metadata. */
  metadata: Record<string, unknown>;
}

// ── Alert Builder ────────────────────────────────────────────────────────────

let _alertSeq = 0;

/** Generate a unique alert ID. */
export function nextAlertId(): string {
  return `bea-${Date.now()}-${++_alertSeq}`;
}

/** Build a BusinessEntityAlert with sensible defaults. */
export function buildAlert(opts: {
  entityId: string;
  entityType: BusinessEntityType;
  category: AlertCategory;
  severity: BusinessEntitySeverity;
  title: string;
  description: string;
  source: string;
  priority?: number;
  action?: AlertAction;
  relatedEntityIds?: string[];
  expiresAt?: string;
  metadata?: Record<string, unknown>;
}): BusinessEntityAlert {
  return {
    id: nextAlertId(),
    entityId: opts.entityId,
    entityType: opts.entityType,
    category: opts.category,
    severity: opts.severity,
    title: opts.title,
    description: opts.description,
    source: opts.source,
    priority: opts.priority ?? severityToPriority(opts.severity),
    action: opts.action ?? null,
    relatedEntityIds: opts.relatedEntityIds ?? [],
    createdAt: new Date().toISOString(),
    expiresAt: opts.expiresAt ?? null,
    acknowledged: false,
    metadata: opts.metadata ?? {},
  };
}

function severityToPriority(s: BusinessEntitySeverity): number {
  switch (s) {
    case "critical": return 1;
    case "high":     return 2;
    case "medium":   return 3;
    case "low":      return 4;
    case "info":     return 5;
  }
}
