/**
 * business-entity-recommendations.ts
 *
 * BUSINESS-ENTITIES-CORE-01
 * Common recommendation model for all Digital Business Entities.
 *
 * Every recommendation carries suggestedOnly: true until
 * Action Engine with approvals is implemented.
 *
 * David and other copilot agents will consume these recommendations.
 *
 * No Prisma. No React. Pure domain types.
 */

import type { BusinessEntityType } from "./business-entity-types";
import type { BusinessEntitySeverity } from "./business-entity-state";

// ── Business Entity Recommendation ───────────────────────────────────────────

/**
 * A suggested action for a business entity.
 *
 * Recommendations are generated by domain engines and consumed by
 * dashboards, copilots (David), and future Action Engine.
 *
 * RULE: All recommendations must carry suggestedOnly: true until
 * Action Engine with approval workflows is implemented.
 */
export interface BusinessEntityRecommendation {
  /** Unique recommendation ID. */
  id: string;
  /** The entity this recommendation targets. */
  entityId: string;
  /** Entity type. */
  entityType: BusinessEntityType;
  /** Priority for ordering (lower = higher priority). */
  priority: number;
  /** Severity / urgency level. */
  severity: BusinessEntitySeverity;
  /** Short title (suitable for list views). */
  title: string;
  /** Detailed description of the recommendation. */
  description: string;
  /** Specific action recommended. */
  recommendedAction: string;
  /** Source engine that generated this recommendation. */
  source: string;
  /** Confidence level (0-100). */
  confidence: number;
  /**
   * MANDATORY: true until Action Engine with approvals exists.
   * Indicates this is a suggestion only, not an automated action.
   */
  suggestedOnly: true;
  /** IDs of related entities. */
  relatedEntityIds: string[];
  /** ISO timestamp when the recommendation was generated. */
  createdAt: string;
  /** Arbitrary domain-specific metadata. */
  metadata: Record<string, unknown>;
}

// ── Recommendation Builder ───────────────────────────────────────────────────

let _recSeq = 0;

/** Generate a unique recommendation ID. */
export function nextRecommendationId(): string {
  return `ber-${Date.now()}-${++_recSeq}`;
}

/** Build a BusinessEntityRecommendation with sensible defaults. */
export function buildRecommendation(opts: {
  entityId: string;
  entityType: BusinessEntityType;
  severity: BusinessEntitySeverity;
  title: string;
  description: string;
  recommendedAction: string;
  source: string;
  priority?: number;
  confidence?: number;
  relatedEntityIds?: string[];
  metadata?: Record<string, unknown>;
}): BusinessEntityRecommendation {
  return {
    id: nextRecommendationId(),
    entityId: opts.entityId,
    entityType: opts.entityType,
    priority: opts.priority ?? 5,
    severity: opts.severity,
    title: opts.title,
    description: opts.description,
    recommendedAction: opts.recommendedAction,
    source: opts.source,
    confidence: opts.confidence ?? 70,
    suggestedOnly: true,
    relatedEntityIds: opts.relatedEntityIds ?? [],
    createdAt: new Date().toISOString(),
    metadata: opts.metadata ?? {},
  };
}
