// AGENTIK-BOARD-INTELLIGENCE-01 — Phase 40: Canonical Board Scenarios

import type { BoardDomain, BoardPriorityLevel, BoardOutcome } from "./board-intelligence-types";

export interface CanonicalBoardScenario {
  readonly id:            string;
  readonly type:          string;
  readonly title:         string;
  readonly description:   string;
  readonly primaryDomain: BoardDomain;
  readonly suggestedOutcome: BoardOutcome;
  readonly priority:      BoardPriorityLevel;
  readonly expectedRisks: string[];
  readonly expectedRecommendations: string[];
  readonly limitations:   string[];
}

export const CANONICAL_BOARD_SCENARIOS: CanonicalBoardScenario[] = [
  {
    id:             "board_canon_001",
    type:           "CRISIS_LIQUIDEZ_CRITICA",
    title:          "Crisis de liquidez crítica con riesgo sistémico",
    description:    "La organización enfrenta una crisis de liquidez que amenaza la continuidad operativa. El flujo de caja cubre menos del 30% de las obligaciones de corto plazo.",
    primaryDomain:  "FINANCE",
    suggestedOutcome: "ESCALATE",
    priority:       "CRITICAL",
    expectedRisks:  ["Incumplimiento de obligaciones financieras", "Paralización operativa", "Pérdida de confianza de acreedores"],
    expectedRecommendations: ["Activar línea de crédito de emergencia", "Revisar y postergar capex no crítico", "Negociar extensión de plazos con proveedores clave"],
    limitations:    ["suggestedOnly: true", "Requiere validación financiera independiente antes de cualquier acción"],
  },
  {
    id:             "board_canon_002",
    type:           "EXPANSION_MERCADO_ESTRATEGICA",
    title:          "Expansión estratégica a nuevo mercado regional",
    description:    "Oportunidad de expansión a un mercado adyacente con alto potencial de crecimiento. Requiere inversión significativa y ajuste organizacional.",
    primaryDomain:  "COMMERCIAL",
    suggestedOutcome: "APPROVE_WITH_CONDITIONS",
    priority:       "HIGH",
    expectedRisks:  ["Sobreextensión de recursos operativos", "Competencia establecida en nuevo mercado", "Riesgo regulatorio local"],
    expectedRecommendations: ["Realizar análisis de mercado profundo antes de inversión", "Iniciar con operación piloto de bajo riesgo", "Asegurar financiamiento dedicado para expansión"],
    limitations:    ["suggestedOnly: true", "Validar con estudio de mercado local"],
  },
  {
    id:             "board_canon_003",
    type:           "INCUMPLIMIENTO_REGULATORIO",
    title:          "Riesgo de incumplimiento regulatorio crítico",
    description:    "Se identificaron brechas en el cumplimiento de regulaciones vigentes que podrían derivar en sanciones significativas o suspensión de operaciones.",
    primaryDomain:  "COMPLIANCE",
    suggestedOutcome: "ESCALATE",
    priority:       "CRITICAL",
    expectedRisks:  ["Sanciones regulatorias", "Suspensión de licencias operativas", "Daño reputacional severo"],
    expectedRecommendations: ["Activar protocolo de remediación inmediata", "Involucrar asesoría legal externa", "Notificación preventiva a reguladores si aplica"],
    limitations:    ["suggestedOnly: true", "Requiere revisión legal antes de cualquier comunicación regulatoria"],
  },
  {
    id:             "board_canon_004",
    type:           "TRANSFORMACION_DIGITAL",
    title:          "Transformación digital de procesos core",
    description:    "Propuesta de transformación digital de los procesos operativos principales para mejorar eficiencia y reducir costos operativos en 20-35%.",
    primaryDomain:  "TECHNOLOGY",
    suggestedOutcome: "APPROVE_WITH_CONDITIONS",
    priority:       "HIGH",
    expectedRisks:  ["Interrupción operativa durante migración", "Resistencia al cambio organizacional", "Dependencia tecnológica de nuevos proveedores"],
    expectedRecommendations: ["Desarrollar roadmap de implementación por fases", "Invertir en capacitación del equipo", "Mantener sistemas legacy en paralelo durante transición"],
    limitations:    ["suggestedOnly: true", "Evaluar con CTO y equipo técnico antes de aprobar"],
  },
  {
    id:             "board_canon_005",
    type:           "PERDIDA_CLIENTE_ESTRATEGICO",
    title:          "Pérdida de cliente estratégico de alto valor",
    description:    "Un cliente que representa el 25-40% de los ingresos ha notificado la terminación del contrato o muestra señales claras de salida.",
    primaryDomain:  "COMMERCIAL",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "CRITICAL",
    expectedRisks:  ["Caída significativa de ingresos", "Impacto en flujo de caja", "Pérdida de reputación sectorial"],
    expectedRecommendations: ["Activar protocolo de retención de cuenta", "Diversificar portafolio de clientes inmediatamente", "Revisar propuesta de valor y pricing"],
    limitations:    ["suggestedOnly: true", "Verificar términos contractuales antes de acciones de retención"],
  },
  {
    id:             "board_canon_006",
    type:           "DETERIORO_GOBIERNO_CORPORATIVO",
    title:          "Deterioro estructural del gobierno corporativo",
    description:    "Se detectaron múltiples debilidades en los controles internos, segregación de funciones y políticas de gobierno que elevan el riesgo operacional y fiduciario.",
    primaryDomain:  "GOVERNANCE",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "CRITICAL",
    expectedRisks:  ["Fraude interno no detectado", "Irregularidades en reportes financieros", "Exposición a litigios"],
    expectedRecommendations: ["Auditoría interna inmediata de controles críticos", "Fortalecer comité de auditoría", "Implementar sistema de denuncias anónimas"],
    limitations:    ["suggestedOnly: true", "Involucrar auditoría externa independiente"],
  },
  {
    id:             "board_canon_007",
    type:           "CONFLICTO_ESTRATEGICO",
    title:          "Conflicto entre objetivos estratégicos de largo plazo",
    description:    "Existe una tensión estructural entre dos líneas estratégicas de la organización que genera desperdicio de recursos y confusión organizacional.",
    primaryDomain:  "STRATEGY",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Ineficiencia en asignación de recursos", "Desmotivación del equipo directivo", "Pérdida de ventaja competitiva"],
    expectedRecommendations: ["Sesión de alineación estratégica de alta dirección", "Redefinir prioridades con criterios explícitos", "Actualizar plan estratégico con resolución de conflicto"],
    limitations:    ["suggestedOnly: true", "Requiere facilitación experta en planeación estratégica"],
  },
  {
    id:             "board_canon_008",
    type:           "OPORTUNIDAD_ADQUISICION",
    title:          "Oportunidad de adquisición estratégica",
    description:    "Se presenta una oportunidad para adquirir un competidor o empresa complementaria que podría acelerar el crecimiento y consolidar posición de mercado.",
    primaryDomain:  "STRATEGY",
    suggestedOutcome: "APPROVE_WITH_CONDITIONS",
    priority:       "HIGH",
    expectedRisks:  ["Valoración incorrecta del activo", "Pasivos ocultos", "Riesgo de integración cultural"],
    expectedRecommendations: ["Due diligence financiero y legal completo", "Análisis de fit cultural y operativo", "Estructura de financiamiento que no comprometa solidez financiera"],
    limitations:    ["suggestedOnly: true", "Due diligence externo obligatorio antes de aprobación"],
  },
  {
    id:             "board_canon_009",
    type:           "CRISIS_REPUTACIONAL",
    title:          "Crisis reputacional con exposición pública",
    description:    "La organización enfrenta una crisis reputacional con cobertura mediática que afecta la percepción de clientes, empleados e inversores.",
    primaryDomain:  "RISK",
    suggestedOutcome: "ESCALATE",
    priority:       "CRITICAL",
    expectedRisks:  ["Pérdida de clientes por desconfianza", "Dificultad para retener talento clave", "Impacto negativo en términos de financiamiento"],
    expectedRecommendations: ["Activar protocolo de crisis de comunicaciones", "Comunicación proactiva con stakeholders clave", "Acciones correctivas visibles y medibles"],
    limitations:    ["suggestedOnly: true", "Coordinar con asesoría de comunicaciones de crisis"],
  },
  {
    id:             "board_canon_010",
    type:           "DETERIORO_OPERATIVO_SISTÉMICO",
    title:          "Deterioro operativo sistémico multi-área",
    description:    "Múltiples áreas operativas muestran degradación simultánea en KPIs de eficiencia, calidad y satisfacción del cliente, sugiriendo un problema estructural.",
    primaryDomain:  "OPERATIONS",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Pérdida acelerada de participación de mercado", "Incremento de costos por ineficiencias", "Alta rotación de personal operativo"],
    expectedRecommendations: ["Diagnóstico operativo integral", "Plan de mejora operativa con métricas claras", "Revisión de estructura organizacional de operaciones"],
    limitations:    ["suggestedOnly: true", "Validar con diagnóstico operativo externo"],
  },
  {
    id:             "board_canon_011",
    type:           "RIESGO_CONCENTRACION_PROVEEDOR",
    title:          "Riesgo crítico de concentración en proveedores estratégicos",
    description:    "Más del 60% del suministro crítico depende de 1-2 proveedores estratégicos con señales de inestabilidad financiera o geopolítica.",
    primaryDomain:  "RISK",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Interrupción de cadena de suministro", "Incremento de precios sin alternativas", "Riesgo operativo por dependencia unilateral"],
    expectedRecommendations: ["Diversificación urgente de base de proveedores", "Inventarios estratégicos de seguridad", "Contratos de largo plazo con cláusulas de continuidad"],
    limitations:    ["suggestedOnly: true", "Evaluar con gestión de supply chain"],
  },
  {
    id:             "board_canon_012",
    type:           "CAIDA_RENTABILIDAD_ESTRUCTURAL",
    title:          "Caída estructural de rentabilidad por presión de márgenes",
    description:    "Los márgenes operativos han caído consistentemente durante 3+ períodos consecutivos, indicando presiones estructurales en el modelo de negocio.",
    primaryDomain:  "FINANCE",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "CRITICAL",
    expectedRisks:  ["Deterioro de flujo de caja operativo", "Dificultad para invertir en crecimiento", "Riesgo de incumplimiento de covenants financieros"],
    expectedRecommendations: ["Revisión integral del modelo de costos", "Análisis de pricing y mix de productos", "Plan de restructuración operativa"],
    limitations:    ["suggestedOnly: true", "Requiere análisis financiero profundo y contexto de mercado"],
  },
  {
    id:             "board_canon_013",
    type:           "RIESGO_CIBERSEGURIDAD",
    title:          "Riesgo crítico de ciberseguridad y protección de datos",
    description:    "Se identificaron vulnerabilidades críticas en la infraestructura tecnológica que exponen datos de clientes y operaciones a amenazas cibernéticas.",
    primaryDomain:  "TECHNOLOGY",
    suggestedOutcome: "ESCALATE",
    priority:       "CRITICAL",
    expectedRisks:  ["Violación de datos sensibles", "Interrupción de operaciones por ransomware", "Sanciones por GDPR/LGPD u otras regulaciones de privacidad"],
    expectedRecommendations: ["Auditoría de ciberseguridad externa inmediata", "Plan de remediación de vulnerabilidades críticas", "Programa de respuesta a incidentes cibernéticos"],
    limitations:    ["suggestedOnly: true", "Involucrar CISO y expertos externos de ciberseguridad"],
  },
  {
    id:             "board_canon_014",
    type:           "CONFLICTO_PRIORIDADES_INVERSION",
    title:          "Conflicto en prioridades de asignación de capital",
    description:    "Múltiples proyectos estratégicos compiten por capital limitado, generando tensión entre inversión en crecimiento, mejora operativa y servicio de deuda.",
    primaryDomain:  "STRATEGY",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Subinversión en áreas críticas", "Proyectos estratégicos en riesgo por falta de recursos", "Costo de oportunidad por mala asignación"],
    expectedRecommendations: ["Matriz de priorización estratégica de inversiones", "Definición de criterios de asignación de capital", "Revisión del plan de inversión con perspectiva de ROI"],
    limitations:    ["suggestedOnly: true", "Validar con CFO y modelo financiero actualizado"],
  },
  {
    id:             "board_canon_015",
    type:           "DETERIORO_TALENTO_CLAVE",
    title:          "Deterioro crítico de retención de talento clave",
    description:    "Alta rotación o señales de salida en posiciones directivas y técnicas críticas que amenazan la continuidad operativa y capacidad de ejecución estratégica.",
    primaryDomain:  "PEOPLE",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Pérdida de conocimiento institucional crítico", "Incapacidad de ejecutar estrategia por brechas de talento", "Costos de reemplazo y curva de aprendizaje"],
    expectedRecommendations: ["Plan de retención con compensación competitiva", "Programas de desarrollo y liderazgo", "Planes de sucesión para posiciones críticas"],
    limitations:    ["suggestedOnly: true", "Involucrar CHRO y análisis de climate organizacional"],
  },
  {
    id:             "board_canon_016",
    type:           "RIESGO_GEOPOLITICO",
    title:          "Exposición a riesgo geopolítico en mercados clave",
    description:    "Cambios en el entorno geopolítico afectan las operaciones, contratos o acceso a mercados en territorios donde la organización tiene presencia significativa.",
    primaryDomain:  "RISK",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Restricciones operativas por cambios regulatorios", "Devaluación de activos en mercados afectados", "Interrupción de relaciones comerciales"],
    expectedRecommendations: ["Análisis de exposición y escenarios de contingencia", "Diversificación geográfica de operaciones", "Cobertura de riesgos cambiarios y políticos"],
    limitations:    ["suggestedOnly: true", "Validar con asesores de riesgo político y legal internacional"],
  },
  {
    id:             "board_canon_017",
    type:           "FUSIÓN_INTEGRACIÓN",
    title:          "Desafíos de integración post-fusión",
    description:    "Una fusión o adquisición reciente enfrenta desafíos de integración que amenazan la captura de sinergias y la estabilidad operativa.",
    primaryDomain:  "OPERATIONS",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["No captura de sinergias prometidas", "Conflictos culturales y organizacionales", "Fuga de talento clave en empresa adquirida"],
    expectedRecommendations: ["PMO de integración con métricas claras", "Comunicación proactiva a todas las partes", "Quick wins de integración para generar confianza"],
    limitations:    ["suggestedOnly: true", "Validar con equipo de integración post-merger"],
  },
  {
    id:             "board_canon_018",
    type:           "RIESGO_MEDIOAMBIENTAL",
    title:          "Exposición a riesgos medioambientales y de sostenibilidad",
    description:    "Las operaciones de la organización presentan riesgos medioambientales significativos o están bajo presión por criterios ESG de clientes e inversores.",
    primaryDomain:  "COMPLIANCE",
    suggestedOutcome: "APPROVE_WITH_CONDITIONS",
    priority:       "MEDIUM",
    expectedRisks:  ["Sanciones regulatorias medioambientales", "Pérdida de contratos por criterios ESG", "Daño reputacional en mercados conscientes"],
    expectedRecommendations: ["Política de sostenibilidad corporativa formal", "Inversión en eficiencia energética y huella de carbono", "Reportes ESG para stakeholders"],
    limitations:    ["suggestedOnly: true", "Involucrar expertos en sostenibilidad y compliance ambiental"],
  },
  {
    id:             "board_canon_019",
    type:           "INNOVACIÓN_DISRUPTIVA",
    title:          "Amenaza de disrupción por innovación de competidores",
    description:    "Competidores o nuevos entrantes están adoptando tecnologías o modelos de negocio disruptivos que amenazan la posición competitiva de la organización.",
    primaryDomain:  "STRATEGY",
    suggestedOutcome: "REVIEW_REQUIRED",
    priority:       "HIGH",
    expectedRisks:  ["Obsolescencia de modelo de negocio actual", "Pérdida gradual de participación de mercado", "Dificultad para atraer inversión si no hay innovación"],
    expectedRecommendations: ["Programa de innovación estructurado", "Partnerships estratégicos con ecosistema tech", "Análisis de build vs buy vs partner para capacidades clave"],
    limitations:    ["suggestedOnly: true", "Validar con análisis competitivo y benchmarking sectorial"],
  },
  {
    id:             "board_canon_020",
    type:           "GOBIERNO_DIVIDENDOS",
    title:          "Decisión estratégica de política de dividendos",
    description:    "La junta debe decidir la política de distribución de utilidades balanceando retorno a accionistas con necesidades de reinversión para crecimiento.",
    primaryDomain:  "GOVERNANCE",
    suggestedOutcome: "APPROVE_WITH_CONDITIONS",
    priority:       "MEDIUM",
    expectedRisks:  ["Insatisfacción de accionistas por bajo retorno", "Subinversión en crecimiento por exceso de distribución", "Señales negativas al mercado"],
    expectedRecommendations: ["Política de dividendos alineada con ciclo de negocio", "Comunicación clara a accionistas sobre criterios", "Revisión anual de la política vs condiciones del negocio"],
    limitations:    ["suggestedOnly: true", "Requiere aprobación formal de asamblea de accionistas"],
  },
];
