/**
 * lib/integrations/oauth/providers/meta-oauth.ts
 *
 * AGENTIK-INTEGRATIONS-VAULT-RUNTIME-01 — Meta OAuth Config
 *
 * Static configuration for Meta (Facebook / Instagram) OAuth 2.0.
 * Covers: Instagram Business, Facebook Pages, WhatsApp Business.
 *
 * IMPORTANT: Never log app secrets. Never return secrets to client layers.
 */

export const META_OAUTH_CONFIG = {
  authorizationUrl: "https://www.facebook.com/v19.0/dialog/oauth",
  tokenUrl:         "https://graph.facebook.com/v19.0/oauth/access_token",
  revokeUrl:        "https://graph.facebook.com/me/permissions",
  /** Required scopes for Instagram publishing */
  instagramScopes: [
    "instagram_basic",
    "instagram_content_publish",
    "pages_read_engagement",
  ] as const,
  /** Required scopes for Facebook Pages */
  facebookScopes: [
    "pages_manage_posts",
    "pages_read_engagement",
    "public_profile",
  ] as const,
  /** Required scopes for WhatsApp Business */
  whatsappScopes: [
    "whatsapp_business_messaging",
    "whatsapp_business_management",
  ] as const,
} as const;

/**
 * Reads Meta app credentials from environment.
 * Throws if any required var is missing.
 */
export function getMetaCredentials(): {
  appId:       string;
  appSecret:   string;
  redirectUri: string;
} {
  const appId       = process.env.META_APP_ID;
  const appSecret   = process.env.META_APP_SECRET;
  const redirectUri = process.env.META_REDIRECT_URI;
  if (!appId || !appSecret || !redirectUri) {
    throw new Error(
      "Missing Meta OAuth env vars: META_APP_ID, META_APP_SECRET, META_REDIRECT_URI",
    );
  }
  return { appId, appSecret, redirectUri };
}

export type MetaOAuthPurpose = "instagram" | "facebook" | "whatsapp";

function scopesForPurpose(purpose: MetaOAuthPurpose): string[] {
  switch (purpose) {
    case "instagram": return [...META_OAUTH_CONFIG.instagramScopes];
    case "facebook":  return [...META_OAUTH_CONFIG.facebookScopes];
    case "whatsapp":  return [...META_OAUTH_CONFIG.whatsappScopes];
  }
}

/**
 * Builds the Meta authorization URL.
 * state must be generated by oauth-session-service.
 * Meta uses standard code flow (no PKCE required for server apps).
 */
export function buildMetaAuthUrl(params: {
  state:    string;
  purpose:  MetaOAuthPurpose;
  scopes?:  string[];
}): string {
  const { appId, redirectUri } = getMetaCredentials();
  const scopes = params.scopes ?? scopesForPurpose(params.purpose);

  const url = new URL(META_OAUTH_CONFIG.authorizationUrl);
  url.searchParams.set("client_id",    appId);
  url.searchParams.set("redirect_uri", redirectUri);
  url.searchParams.set("response_type","code");
  url.searchParams.set("scope",        scopes.join(","));
  url.searchParams.set("state",        params.state);
  return url.toString();
}
