/**
 * lib/integrations/oauth/providers/tiktok-oauth.ts
 *
 * AGENTIK-INTEGRATIONS-VAULT-RUNTIME-01 — TikTok OAuth Config
 *
 * Static configuration for TikTok Business OAuth 2.0.
 * No real OAuth flow here — only config, scope catalog, and URL builder helper.
 *
 * IMPORTANT: Never log client secrets. Never return secrets to client layers.
 */

export const TIKTOK_OAUTH_CONFIG = {
  authorizationUrl: "https://www.tiktok.com/v2/auth/authorize",
  tokenUrl:         "https://open.tiktokapis.com/v2/oauth/token/",
  revokeUrl:        "https://open.tiktokapis.com/v2/oauth/revoke/",
  /** Required scopes for Agentik publishing integration */
  defaultScopes: [
    "user.info.basic",
    "video.upload",
    "video.publish",
  ] as const,
} as const;

export type TikTokScope = typeof TIKTOK_OAUTH_CONFIG.defaultScopes[number];

/**
 * Reads TikTok credentials from environment.
 * Throws if any required var is missing.
 */
export function getTikTokCredentials(): {
  clientKey:    string;
  clientSecret: string;
  redirectUri:  string;
} {
  const clientKey    = process.env.TIKTOK_CLIENT_KEY;
  const clientSecret = process.env.TIKTOK_CLIENT_SECRET;
  const redirectUri  = process.env.TIKTOK_REDIRECT_URI;
  if (!clientKey || !clientSecret || !redirectUri) {
    throw new Error(
      "Missing TikTok OAuth env vars: TIKTOK_CLIENT_KEY, TIKTOK_CLIENT_SECRET, TIKTOK_REDIRECT_URI",
    );
  }
  return { clientKey, clientSecret, redirectUri };
}

/**
 * Builds the TikTok authorization URL for PKCE flow.
 * state and codeChallenge must be generated by oauth-session-service.
 */
export function buildTikTokAuthUrl(params: {
  state:         string;
  codeChallenge: string;
  scopes?:       string[];
}): string {
  const { clientKey, redirectUri } = getTikTokCredentials();
  const scopes = params.scopes ?? [...TIKTOK_OAUTH_CONFIG.defaultScopes];

  const url = new URL(TIKTOK_OAUTH_CONFIG.authorizationUrl);
  url.searchParams.set("client_key",             clientKey);
  url.searchParams.set("response_type",          "code");
  url.searchParams.set("scope",                  scopes.join(","));
  url.searchParams.set("redirect_uri",           redirectUri);
  url.searchParams.set("state",                  params.state);
  url.searchParams.set("code_challenge",         params.codeChallenge);
  url.searchParams.set("code_challenge_method",  "S256");
  return url.toString();
}
