/**
 * xml-signer.ts
 *
 * AGENTIK-DIAN-SECURITY-01
 * DIAN Integration Layer — WS-Security XML Signer
 *
 * Implements OASIS WS-Security XML-DSIG signing for DIAN SOAP requests.
 *
 * Signing specification (DIAN guide Section 2.6):
 *   Algorithm:           RSA-SHA256
 *   Canonicalization:    Exclusive C14N (http://www.w3.org/2001/10/xml-exc-c14n#)
 *   Digest:              SHA-256
 *   Key reference:       BinarySecurityToken (X509v3)
 *   Signed elements:     u:Timestamp, a:To
 *
 * Exclusive C14N implementation:
 *   For our controlled XML (generated by soap-builder.ts), the canonical form
 *   is produced directly by generating compact element strings with namespace
 *   declarations for all visibly-utilized prefixes. This avoids a full
 *   general-purpose C14N parser while producing correct results for DIAN's
 *   specific elements.
 *
 *   Key invariants that make this safe:
 *   1. All element strings are generated by us (controlled input)
 *   2. All namespace prefixes are known and constant
 *   3. Elements have no inheritable state from parent context
 *   4. Attributes are sorted alphabetically (xmlns: first, then regular)
 *
 * Signing flow:
 *   1. Compute SHA-256(C14N(Timestamp)) → DigestValue for Timestamp Reference
 *   2. Compute SHA-256(C14N(To)) → DigestValue for To Reference
 *   3. Build SignedInfo in canonical form (compact, no extra whitespace)
 *   4. Sign RSA-SHA256(C14N(SignedInfo)) → SignatureValue
 *   5. Return BST element + Signature element for injection into SOAP header
 *
 * IMPORTANT: Backend-only. Never import in client components.
 * IMPORTANT: Never log privateKeyPem, certDer, or any intermediate signing values.
 */

import { createSign, createHash } from "node:crypto";
import { DIAN_NAMESPACES } from "../types/dian-types";

// ── Input/output types ────────────────────────────────────────────────────────

/**
 * Canonical element strings produced by soap-builder.ts for signing.
 *
 * Each canonical string is the element in Exclusive C14N form —
 * compact (no extra whitespace), with all needed namespace declarations
 * on the element itself (for correct standalone C14N verification).
 */
export interface SoapSigningInputs {
  /** wsu:Id value on the Timestamp element (e.g. "_ts_1234567890"). */
  timestampId:        string;
  /** Exclusive C14N form of the Timestamp element. */
  timestampCanonical: string;
  /** wsu:Id value on the To element (e.g. "_to_1234567890"). */
  toId:               string;
  /** Exclusive C14N form of the wsa:To element. */
  toCanonical:        string;
}

/**
 * WS-Security signing result.
 *
 * Both XML fragments are injected into the Security header by
 * injectSignatureIntoEnvelope() in soap-builder.ts.
 */
export interface WssSignatureResult {
  /** Id value of the BinarySecurityToken (used in KeyInfo Reference). */
  bstId:         string;
  /** Complete BinarySecurityToken XML element. */
  bstXml:        string;
  /** Complete ds:Signature XML element including SignedInfo + KeyInfo. */
  signatureXml:  string;
}

// ── Main signing function ─────────────────────────────────────────────────────

/**
 * Sign SOAP WS-Security elements with RSA-SHA256.
 *
 * Produces a BinarySecurityToken (BST) and a Signature element for
 * injection into the SOAP Security header.
 *
 * @param inputs        Signing inputs from buildGetAcquirerRequest()
 * @param privateKeyPem RSA private key in PEM format (from parsePkcs12())
 * @param certDer       DER-encoded certificate (from parsePkcs12())
 *
 * @throws DianSigningError on any cryptographic failure
 */
export function signWssElements(
  inputs:        SoapSigningInputs,
  privateKeyPem: string,
  certDer:       Buffer,
): WssSignatureResult {
  const bstId     = `_bst_${Date.now()}`;
  const certB64   = certDer.toString("base64");

  // Step 1: Compute element digests
  let tsDigest: string;
  let toDigest: string;
  try {
    tsDigest = sha256Base64(inputs.timestampCanonical);
    toDigest = sha256Base64(inputs.toCanonical);
  } catch (err) {
    throw new DianSigningError(
      `Failed to compute element digests: ${err instanceof Error ? err.message : "unknown"}`,
    );
  }

  // Step 2: Build SignedInfo in canonical form
  const signedInfoCanonical = buildSignedInfoCanonical(
    inputs.timestampId, tsDigest,
    inputs.toId,        toDigest,
  );

  // Step 3: Sign the canonical SignedInfo
  let signatureValue: string;
  try {
    signatureValue = rsaSha256Sign(signedInfoCanonical, privateKeyPem);
  } catch (err) {
    throw new DianSigningError(
      `RSA-SHA256 signing failed: ${err instanceof Error ? err.message : "unknown"}. ` +
      "Verify the private key PEM is valid and not password-protected.",
    );
  }

  // Step 4: Build output elements
  const bstXml       = buildBstXml(bstId, certB64);
  const signatureXml = buildSignatureXml(bstId, signedInfoCanonical, signatureValue);

  return { bstId, bstXml, signatureXml };
}

// ── Canonical element builders ─────────────────────────────────────────────────

/**
 * Build the Exclusive C14N form of a u:Timestamp element.
 *
 * Output form (compact, no extra whitespace):
 *   <u:Timestamp xmlns:u="...utility..." u:Id="_ts_xxx">
 *   <u:Created>ISO</u:Created><u:Expires>ISO</u:Expires>
 *   </u:Timestamp>
 *
 * Attributes are already in sorted order:
 *   xmlns:u (namespace decl) → u:Id (regular attr)
 */
export function buildCanonicalTimestamp(
  id:      string,
  created: string,
  expires: string,
): string {
  const u = DIAN_NAMESPACES.WSS_UTILITY;
  return (
    `<u:Timestamp xmlns:u="${u}" u:Id="${id}">` +
    `<u:Created>${created}</u:Created>` +
    `<u:Expires>${expires}</u:Expires>` +
    `</u:Timestamp>`
  );
}

/**
 * Build the Exclusive C14N form of a wsa:To element.
 *
 * Output form (compact, attributes sorted):
 *   <a:To xmlns:a="...addressing..." xmlns:u="...utility..." u:Id="_to_xxx">URL</a:To>
 *
 * Attributes sorted:
 *   xmlns:a (a < u alphabetically) → xmlns:u → u:Id (regular attr)
 */
export function buildCanonicalToElement(
  endpointUrl: string,
  toId:        string,
): string {
  const a = DIAN_NAMESPACES.WS_ADDRESSING;
  const u = DIAN_NAMESPACES.WSS_UTILITY;
  return (
    `<a:To xmlns:a="${a}" xmlns:u="${u}" u:Id="${toId}">` +
    escapeXmlText(endpointUrl) +
    `</a:To>`
  );
}

// ── SignedInfo builder ────────────────────────────────────────────────────────

/**
 * Build the ds:SignedInfo element in Exclusive C14N form.
 *
 * This exact string is what gets RSA-SHA256 signed.
 * The receiver applies C14N to the SignedInfo in the received SOAP,
 * then verifies the signature against this value.
 *
 * Compact form (no extra whitespace) ensures deterministic C14N.
 * Empty elements use explicit closing tags per C14N rules.
 */
function buildSignedInfoCanonical(
  timestampId: string,
  tsDigest:    string,
  toId:        string,
  toDigest:    string,
): string {
  const ds      = DIAN_NAMESPACES.XML_DSIG;
  const c14nAlg = DIAN_NAMESPACES.XML_EXC_C14N;
  const sigAlg  = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256";
  const digAlg  = "http://www.w3.org/2001/04/xmlenc#sha256";

  const ref = (id: string, digest: string): string =>
    `<ds:Reference URI="#${id}">` +
    `<ds:Transforms>` +
    `<ds:Transform Algorithm="${c14nAlg}"></ds:Transform>` +
    `</ds:Transforms>` +
    `<ds:DigestMethod Algorithm="${digAlg}"></ds:DigestMethod>` +
    `<ds:DigestValue>${digest}</ds:DigestValue>` +
    `</ds:Reference>`;

  return (
    `<ds:SignedInfo xmlns:ds="${ds}">` +
    `<ds:CanonicalizationMethod Algorithm="${c14nAlg}"></ds:CanonicalizationMethod>` +
    `<ds:SignatureMethod Algorithm="${sigAlg}"></ds:SignatureMethod>` +
    ref(timestampId, tsDigest) +
    ref(toId,        toDigest) +
    `</ds:SignedInfo>`
  );
}

// ── BST and Signature element builders ───────────────────────────────────────

/**
 * Build the WS-Security BinarySecurityToken element.
 *
 * The value is the base64-encoded DER-encoded X.509 certificate.
 * xmlns:o (WSS_SECEXT) and xmlns:u (WSS_UTILITY) are inherited from
 * the parent <o:Security> element, so not re-declared here.
 */
function buildBstXml(bstId: string, certBase64: string): string {
  const x509vt  = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3";
  const b64enc  = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary";
  return (
    `<o:BinarySecurityToken u:Id="${bstId}"` +
    ` ValueType="${x509vt}"` +
    ` EncodingType="${b64enc}">` +
    certBase64 +
    `</o:BinarySecurityToken>`
  );
}

/**
 * Build the complete ds:Signature element.
 *
 * Structure:
 *   <ds:Signature>
 *     <ds:SignedInfo>...</ds:SignedInfo>     ← already in canonical form
 *     <ds:SignatureValue>...</ds:SignatureValue>
 *     <ds:KeyInfo>
 *       <o:SecurityTokenReference>
 *         <o:Reference URI="#_bst_xxx" .../>
 *       </o:SecurityTokenReference>
 *     </ds:KeyInfo>
 *   </ds:Signature>
 */
function buildSignatureXml(
  bstId:             string,
  signedInfoCanonical: string,
  signatureValue:    string,
): string {
  const ds     = DIAN_NAMESPACES.XML_DSIG;
  const x509vt = "http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-x509-token-profile-1.0#X509v3";
  return (
    `<ds:Signature xmlns:ds="${ds}">` +
    signedInfoCanonical +
    `<ds:SignatureValue>${signatureValue}</ds:SignatureValue>` +
    `<ds:KeyInfo>` +
    `<o:SecurityTokenReference>` +
    `<o:Reference URI="#${bstId}" ValueType="${x509vt}"/>` +
    `</o:SecurityTokenReference>` +
    `</ds:KeyInfo>` +
    `</ds:Signature>`
  );
}

// ── Crypto primitives ─────────────────────────────────────────────────────────

function sha256Base64(data: string): string {
  return createHash("sha256").update(data, "utf8").digest("base64");
}

function rsaSha256Sign(data: string, privateKeyPem: string): string {
  const signer = createSign("RSA-SHA256");
  signer.update(data, "utf8");
  return signer.sign(privateKeyPem, "base64");
}

// ── XML text escaping ─────────────────────────────────────────────────────────

function escapeXmlText(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// ── Error ─────────────────────────────────────────────────────────────────────

export class DianSigningError extends Error {
  constructor(message: string) {
    super(`[DIAN Signing] ${message}`);
    this.name = "DianSigningError";
  }
}
