/**
 * lib/collections/auto-task.ts
 *
 * Auto-generates CREAR_ACCION_COBRANZA ActionTasks for high-risk debtors.
 *
 * Triggers:
 *   • Customers with maxDpd > 90 (critical exposure)
 *   • Top 3 debtors by overdueReceivable (regardless of DPD)
 *
 * Deduplication:
 *   Skips a customer if a CREAR_ACCION_COBRANZA task with the same targetId
 *   was created within the last 24 h (sourceModule = "collections_auto").
 *
 * Safe to call from:
 *   • POST /api/internal/collections/auto-tasks (cron)
 *   • generateCarteraAlerts() post-hook
 *   • Manual trigger from collections queue UI
 *
 * Export:
 *   generateCollectionsTasks(orgId, createdBy?) → AutoTaskResult
 */

import { prisma }          from "@/lib/prisma";
import { createActionTask } from "@/lib/actions/service";
import { getCollectionsQueue } from "./queue";
import {
  ActionTaskType,
  ActionTaskPriority,
} from "@prisma/client";

// ── Constants ─────────────────────────────────────────────────────────────────

const SOURCE_MODULE   = "collections_auto";
const DEDUP_WINDOW_MS = 24 * 60 * 60 * 1000; // 24 h

// ── Types ─────────────────────────────────────────────────────────────────────

export interface AutoTaskResult {
  created: number;
  skipped: number;
  errors:  number;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtCOP(n: number): string {
  if (n >= 1_000_000_000) return "$" + (n / 1_000_000_000).toFixed(1) + "B";
  if (n >= 1_000_000)     return "$" + (n / 1_000_000).toFixed(0) + "M";
  return "$" + new Intl.NumberFormat("es-CO", { maximumFractionDigits: 0 }).format(n);
}

async function isDuplicate(organizationId: string, targetId: string): Promise<boolean> {
  const since = new Date(Date.now() - DEDUP_WINDOW_MS);
  const found = await prisma.actionTask.findFirst({
    where: {
      organizationId,
      sourceModule: SOURCE_MODULE,
      targetId,
      actionType:   ActionTaskType.CREAR_ACCION_COBRANZA,
      createdAt:    { gte: since },
    },
    select: { id: true },
  });
  return found !== null;
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Generate collection ActionTasks for +90 DPD customers and top 3 debtors.
 *
 * @param organizationId  Tenant to process.
 * @param createdBy       Actor label (default: "collections_auto").
 */
export async function generateCollectionsTasks(
  organizationId: string,
  createdBy = SOURCE_MODULE,
): Promise<AutoTaskResult> {
  const result: AutoTaskResult = { created: 0, skipped: 0, errors: 0 };

  // Fetch full queue (sorted by risk)
  let queue;
  try {
    queue = await getCollectionsQueue(organizationId, 100);
  } catch (err) {
    console.error("[collections/auto-task] queue fetch error:", err);
    result.errors++;
    return result;
  }

  if (queue.length === 0) return result;

  // ── Target set: +90 DPD customers + top 3 debtors ────────────────────────
  const critical90    = queue.filter(r => r.maxDpd > 90);
  const top3Debtors   = queue.slice(0, 3);

  // Deduplicate the combined set by slug
  const seen  = new Set<string>();
  const targets = [...critical90, ...top3Debtors].filter(r => {
    if (seen.has(r.slug)) return false;
    seen.add(r.slug);
    return true;
  });

  for (const debtor of targets) {
    try {
      const isDupe = await isDuplicate(organizationId, debtor.slug);
      if (isDupe) {
        result.skipped++;
        continue;
      }

      const action = debtor.suggestedAction;

      await createActionTask(organizationId, createdBy, {
        title: `[COBRANZA AUTO] ${debtor.name} — ${fmtCOP(debtor.overdueReceivable)} vencido`,
        description: [
          `Cliente: ${debtor.name}${debtor.nit ? ` (NIT ${debtor.nit})` : ""}`,
          `Cartera vencida: ${fmtCOP(debtor.overdueReceivable)} · DPD máximo: ${debtor.maxDpd > 0 ? `+${debtor.maxDpd}d` : "Al día"}`,
          `Acción sugerida: ${action.label}`,
          ``,
          `Guión: ${action.scriptHint}`,
          debtor.sellerName ? `Vendedor asignado: ${debtor.sellerName}` : "",
        ].filter(l => l !== "").join("\n"),
        actionType:   ActionTaskType.CREAR_ACCION_COBRANZA,
        targetType:   "customer",
        targetId:     debtor.slug,
        targetLabel:  debtor.name,
        sourceModule: SOURCE_MODULE,
        priority:     action.priority === "URGENT" ? ActionTaskPriority.URGENT
                    : action.priority === "HIGH"   ? ActionTaskPriority.HIGH
                    : action.priority === "MEDIUM" ? ActionTaskPriority.MEDIUM
                    : ActionTaskPriority.LOW,
        dueAt:        new Date(Date.now() + 24 * 60 * 60 * 1000), // due in 24h
        payloadJson: {
          autoGenerated:     true,
          overdueReceivable: debtor.overdueReceivable,
          maxDpd:            debtor.maxDpd,
          riskTier:          debtor.riskTier,
          riskScore:         debtor.riskScore,
          suggestedChannel:  action.channel,
          scriptHint:        action.scriptHint,
          nit:               debtor.nit,
          city:              debtor.city,
          sellerName:        debtor.sellerName,
        },
      });

      result.created++;
    } catch (err) {
      console.error(`[collections/auto-task] error for ${debtor.slug}:`, err);
      result.errors++;
    }
  }

  return result;
}
