/**
 * lib/security/anomaly/anomaly-types.ts
 *
 * AGENTIK-SECURITY-ANOMALY-DETECTION-01
 * Core Domain Types — Anomaly Detection Layer
 *
 * No server-only. No Prisma. Pure domain contracts.
 * Everything is serializable. Multi-tenant mandatory.
 */

// ── AnomalyType ───────────────────────────────────────────────────────────────

export type AnomalyType =
  | "LOGIN_FAILURE_SPIKE"
  | "MFA_FAILURE_SPIKE"
  | "NEW_DEVICE"
  | "NEW_COUNTRY"
  | "NEW_IP"
  | "VAULT_ACCESS_SPIKE"
  | "KMS_USAGE_SPIKE"
  | "SECRET_ROTATION_SPIKE"
  | "PRIVILEGE_ESCALATION"
  | "CROSS_TENANT_ATTEMPT"
  | "AGENT_PERMISSION_VIOLATION"
  | "UNUSUAL_ACTIVITY"
  | "HIGH_RISK_SESSION"
  | "UNKNOWN";

// ── AnomalySeverity ───────────────────────────────────────────────────────────

export type AnomalySeverity = "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";

// ── AnomalyStatus ─────────────────────────────────────────────────────────────

export type AnomalyStatus = "OPEN" | "ACKNOWLEDGED" | "RESOLVED" | "IGNORED";

// ── AnomalyAuditEventType ─────────────────────────────────────────────────────

export type AnomalyAuditEventType =
  | "ANOMALY_DETECTED"
  | "ANOMALY_ACKNOWLEDGED"
  | "ANOMALY_RESOLVED"
  | "ANOMALY_IGNORED"
  | "ANOMALY_CORRELATED"
  | "ANOMALY_RISK_SCORED";

// ── AnomalySignal ─────────────────────────────────────────────────────────────

/**
 * AnomalySignal — a single detection event produced by one detector.
 * Serializable. Never contains raw secrets, OTP codes, or passwords.
 */
export interface AnomalySignal {
  id:          string;
  type:        AnomalyType;
  orgSlug:     string;
  userId?:     string;
  agentId?:    string;
  sessionId?:  string;
  resource?:   string;
  severity:    AnomalySeverity;
  /** Weighted contribution to total risk score (0–100). */
  weight:      number;
  reason:      string;
  /** Serializable metadata — never raw secrets. */
  metadata:    Record<string, unknown>;
  detectorId:  string;
  occurredAt:  string;   // ISO 8601
  windowStart: string;   // ISO 8601 — start of detection window
  windowEnd:   string;   // ISO 8601 — end of detection window
}

// ── AnomalyAlert ──────────────────────────────────────────────────────────────

/**
 * AnomalyAlert — correlated set of signals forming an actionable alert.
 * Serializable. Carries enough context for operator review without raw secrets.
 */
export interface AnomalyAlert {
  id:              string;
  type:            AnomalyType;
  orgSlug:         string;
  severity:        AnomalySeverity;
  status:          AnomalyStatus;
  title:           string;
  description:     string;
  signals:         AnomalySignal[];
  riskScore:       number;   // 0–100
  createdAt:       string;   // ISO 8601
  updatedAt:       string;   // ISO 8601
  resolvedAt?:     string;   // ISO 8601
  acknowledgedBy?: string;
  resolvedBy?:     string;
  /** Serializable metadata. */
  metadata:        Record<string, unknown>;
  /** True if generated by correlation of multiple signals. */
  isCorrelated:    boolean;
  /** Detector ID or correlation rule that generated this alert. */
  sourceRule:      string;
}

// ── AnomalyEvaluation ─────────────────────────────────────────────────────────

/**
 * AnomalyEvaluation — the full output of a detection pass.
 * Returned by the main anomaly engine after running all detectors.
 */
export interface AnomalyEvaluation {
  orgSlug:     string;
  detected:    boolean;
  signals:     AnomalySignal[];
  alerts:      AnomalyAlert[];
  riskScore:   number;       // 0–100
  severity:    AnomalySeverity;
  reasons:     string[];
  evaluatedAt: string;       // ISO 8601
}

// ── AnomalyDetectorMetadata ───────────────────────────────────────────────────

export interface AnomalyDetectorMetadata {
  id:          string;
  name:        string;
  description: string;
  detects:     AnomalyType[];
  enabled:     boolean;
  version:     string;
}

// ── AnomalyContext ────────────────────────────────────────────────────────────

/**
 * AnomalyContext — input to all detectors.
 * Contains event metadata. NEVER include raw secrets, OTP codes, or passwords.
 */
export interface AnomalyContext {
  orgSlug:    string;
  userId?:    string;
  agentId?:   string;
  sessionId?: string;
  ipAddress?: string;
  userAgent?: string;
  deviceId?:  string;
  country?:   string;
  resource?:  string;
  operation?: string;
  timestamp:  string;  // ISO 8601
  /** Serializable event payload. No raw secrets. */
  eventData:  Record<string, unknown>;
}

// ── AnomalyResult ─────────────────────────────────────────────────────────────

export type AnomalyResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: string; severity?: AnomalySeverity };

// ── Constants ─────────────────────────────────────────────────────────────────

/** Risk score boundary for LOW severity. */
export const ANOMALY_RISK_THRESHOLD_LOW      = 25;
/** Risk score boundary for MEDIUM severity. */
export const ANOMALY_RISK_THRESHOLD_MEDIUM   = 50;
/** Risk score boundary for HIGH severity. */
export const ANOMALY_RISK_THRESHOLD_HIGH     = 75;
/** Risk score boundary for CRITICAL severity. */
export const ANOMALY_RISK_THRESHOLD_CRITICAL = 90;

/** Signal weight for LOW-severity signals. */
export const ANOMALY_WEIGHT_LOW      = 15;
/** Signal weight for MEDIUM-severity signals. */
export const ANOMALY_WEIGHT_MEDIUM   = 30;
/** Signal weight for HIGH-severity signals. */
export const ANOMALY_WEIGHT_HIGH     = 60;
/** Signal weight for CRITICAL-severity signals. */
export const ANOMALY_WEIGHT_CRITICAL = 90;

/** Agents monitored by the Agent Anomaly Detector. */
export const MONITORED_AGENT_IDS: string[] = [
  "luca", "diego", "mila", "laura", "sofia", "pablo",
];
