/**
 * lib/copilot/memory-graph/edge-builder.ts
 *
 * AGENTIK-INTELLIGENCE-MEMORY-GRAPH-01
 * Memory Graph — Edge Factory
 *
 * Create typed, traceable, org-scoped edges between nodes.
 * Every edge MUST have:
 *   - explicit source (provenance)
 *   - explicit reasoning (why this relationship exists)
 *   - same orgSlug on both source and target
 *
 * No implicit edges. No inferred edges without evidence.
 */

import type { GraphEdge, GraphEdgeType } from "./memory-graph-types";
import { generateEdgeId } from "./graph-identity";
import { GRAPH_DEFAULT_WEIGHT } from "./memory-graph-types";

// ── Base factory ───────────────────────────────────────────────────────────────

export interface BuildEdgeInput {
  orgSlug:       string;
  type:          GraphEdgeType;
  sourceNodeId:  string;
  targetNodeId:  string;
  /** Why does this relationship exist? Required. */
  reasoning:     string;
  /** Provenance — what created this edge. Required. */
  source:        string;
  label?:        string;
  weight?:       number;
  metadata?:     Record<string, unknown>;
}

/**
 * buildEdge — create a GraphEdge.
 * Always requires reasoning (no silent/implicit edges).
 */
export function buildEdge(input: BuildEdgeInput): GraphEdge {
  if (input.sourceNodeId === input.targetNodeId) {
    throw new Error("Self-referential edges are not allowed");
  }
  return {
    id:           generateEdgeId(),
    orgSlug:      input.orgSlug,
    type:         input.type,
    sourceNodeId: input.sourceNodeId,
    targetNodeId: input.targetNodeId,
    weight:       input.weight ?? GRAPH_DEFAULT_WEIGHT,
    label:        input.label,
    metadata:     input.metadata ?? {},
    source:       input.source,
    reasoning:    input.reasoning,
    createdAt:    new Date().toISOString(),
  };
}

// ── Semantic edge builders ─────────────────────────────────────────────────────

/** buildRelatedToEdge — generic relationship. */
export function buildRelatedToEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.5,
): GraphEdge {
  return buildEdge({ orgSlug, type: "RELATED_TO", sourceNodeId, targetNodeId, reasoning, source, weight });
}

/** buildGeneratedByEdge — output was generated by an entity. */
export function buildGeneratedByEdge(
  orgSlug: string,
  outputNodeId: string,
  generatorNodeId: string,
  reasoning: string,
  source: string,
): GraphEdge {
  return buildEdge({
    orgSlug, type: "GENERATED_BY", sourceNodeId: outputNodeId,
    targetNodeId: generatorNodeId, reasoning, source, weight: 0.8,
  });
}

/** buildReferencesEdge — node A references node B. */
export function buildReferencesEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
): GraphEdge {
  return buildEdge({ orgSlug, type: "REFERENCES", sourceNodeId, targetNodeId, reasoning, source, weight: 0.6 });
}

/** buildCausedEdge — node A caused node B. */
export function buildCausedEdge(
  orgSlug: string,
  causeNodeId: string,
  effectNodeId: string,
  reasoning: string,
  source: string,
  confidence = 0.7,
): GraphEdge {
  return buildEdge({
    orgSlug, type: "CAUSED", sourceNodeId: causeNodeId,
    targetNodeId: effectNodeId, reasoning, source, weight: confidence,
  });
}

/** buildAffectsEdge — node A affects node B. */
export function buildAffectsEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.7,
): GraphEdge {
  return buildEdge({ orgSlug, type: "AFFECTS", sourceNodeId, targetNodeId, reasoning, source, weight });
}

/** buildBelongsToEdge — node A belongs to container node B. */
export function buildBelongsToEdge(
  orgSlug: string,
  childNodeId: string,
  parentNodeId: string,
  reasoning: string,
  source: string,
): GraphEdge {
  return buildEdge({
    orgSlug, type: "BELONGS_TO", sourceNodeId: childNodeId,
    targetNodeId: parentNodeId, reasoning, source, weight: 0.9,
  });
}

/** buildLinkedToEdge — weak association between two entities. */
export function buildLinkedToEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.4,
): GraphEdge {
  return buildEdge({ orgSlug, type: "LINKED_TO", sourceNodeId, targetNodeId, reasoning, source, weight });
}

/** buildCreatedFromEdge — output was created from an input entity. */
export function buildCreatedFromEdge(
  orgSlug: string,
  outputNodeId: string,
  inputNodeId: string,
  reasoning: string,
  source: string,
): GraphEdge {
  return buildEdge({
    orgSlug, type: "CREATED_FROM", sourceNodeId: outputNodeId,
    targetNodeId: inputNodeId, reasoning, source, weight: 0.75,
  });
}

/** buildResolvesEdge — node A resolves problem node B. */
export function buildResolvesEdge(
  orgSlug: string,
  resolutionNodeId: string,
  problemNodeId: string,
  reasoning: string,
  source: string,
): GraphEdge {
  return buildEdge({
    orgSlug, type: "RESOLVES", sourceNodeId: resolutionNodeId,
    targetNodeId: problemNodeId, reasoning, source, weight: 0.85,
  });
}

/** buildTriggersEdge — node A triggers node B. */
export function buildTriggersEdge(
  orgSlug: string,
  triggerNodeId: string,
  triggeredNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.8,
): GraphEdge {
  return buildEdge({ orgSlug, type: "TRIGGERS", sourceNodeId: triggerNodeId, targetNodeId: triggeredNodeId, reasoning, source, weight });
}

/** buildSupportsEdge — node A supports claim/entity B. */
export function buildSupportsEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.7,
): GraphEdge {
  return buildEdge({ orgSlug, type: "SUPPORTS", sourceNodeId, targetNodeId, reasoning, source, weight });
}

/** buildContradictsEdge — node A contradicts node B. */
export function buildContradictsEdge(
  orgSlug: string,
  sourceNodeId: string,
  targetNodeId: string,
  reasoning: string,
  source: string,
  weight = 0.6,
): GraphEdge {
  return buildEdge({ orgSlug, type: "CONTRADICTS", sourceNodeId, targetNodeId, reasoning, source, weight });
}

// ── Domain-specific edge patterns ─────────────────────────────────────────────

/**
 * orderBelongsToClient — canonical pattern: Order → Client
 */
export function orderBelongsToClient(orgSlug: string, orderNodeId: string, clientNodeId: string): GraphEdge {
  return buildBelongsToEdge(orgSlug, orderNodeId, clientNodeId, "Order is placed by this client", "domain-pattern");
}

/**
 * campaignAffectsProduct — canonical pattern: Campaign → Product
 */
export function campaignAffectsProduct(orgSlug: string, campaignNodeId: string, productNodeId: string): GraphEdge {
  return buildAffectsEdge(orgSlug, campaignNodeId, productNodeId, "Campaign promotes or targets this product", "domain-pattern");
}

/**
 * insightGeneratedByEvidence — canonical pattern: Insight ← Evidence
 */
export function insightGeneratedByEvidence(orgSlug: string, insightNodeId: string, evidenceNodeId: string): GraphEdge {
  return buildGeneratedByEdge(orgSlug, insightNodeId, evidenceNodeId, "Insight derived from this evidence", "intelligence-integration");
}

/**
 * anomalyTriggersAlert — canonical pattern: Anomaly → Alert
 */
export function anomalyTriggersAlert(orgSlug: string, anomalyNodeId: string, alertNodeId: string): GraphEdge {
  return buildTriggersEdge(orgSlug, anomalyNodeId, alertNodeId, "Anomaly detection triggered this alert", "anomaly-integration");
}

/**
 * playbookTriggersTask — canonical pattern: Playbook → Task
 */
export function playbookTriggersTask(orgSlug: string, playbookNodeId: string, taskNodeId: string): GraphEdge {
  return buildTriggersEdge(orgSlug, playbookNodeId, taskNodeId, "Playbook execution initiated this task", "playbook-integration");
}
