// AGENTIK-EXECUTIVE-COUNCIL-01 — Phase 41: Canonical Council Scenarios
// 15 canonical business scenarios for the executive council deliberation layer.

import type { CouncilPerspective, CouncilOutcome } from "./executive-council-types";

export interface CanonicalCouncilScenario {
  readonly type:                  string;
  readonly title:                 string;
  readonly description:           string;
  readonly primaryPerspectives:   CouncilPerspective[];
  readonly secondaryPerspectives: CouncilPerspective[];
  readonly expectedOutcome:       CouncilOutcome;
  readonly keyDisagreements:      string[];
  readonly keyConsensusPoints:    string[];
  readonly topRecommendationTitles: string[];
  readonly limitations:           string[];
}

export const CANONICAL_COUNCIL_SCENARIOS: CanonicalCouncilScenario[] = [
  {
    type:                  "CRISIS_LIQUIDEZ",
    title:                 "Crisis de Liquidez",
    description:           "Flujo de caja negativo por más de 30 días con cartera vencida elevada",
    primaryPerspectives:   ["FINANCE", "COLLECTIONS", "EXECUTIVE"],
    secondaryPerspectives: ["COMMERCIAL", "OPERATIONS"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Ritmo de reducción de gastos vs impacto comercial"],
    keyConsensusPoints:    ["Priorizar cobros inmediatos", "Posponer inversiones no críticas"],
    topRecommendationTitles: [
      "Activar plan de cobro acelerado",
      "Congelar gastos no operativos",
      "Negociar extensión de línea de crédito",
    ],
    limitations:           ["Datos de flujo proyectado pueden variar", "suggestedOnly: true"],
  },
  {
    type:                  "EXPANSION_COMERCIAL",
    title:                 "Expansión Comercial",
    description:           "Oportunidad de crecimiento en nuevo segmento o canal de ventas",
    primaryPerspectives:   ["COMMERCIAL", "STRATEGY", "FINANCE"],
    secondaryPerspectives: ["MARKETING", "OPERATIONS"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Velocidad de expansión vs solidez financiera"],
    keyConsensusPoints:    ["Validar demanda antes de inversión", "Asignar presupuesto piloto"],
    topRecommendationTitles: [
      "Lanzar piloto en segmento objetivo",
      "Definir métricas de éxito a 90 días",
      "Asignar equipo comercial dedicado",
    ],
    limitations:           ["Proyecciones de mercado son estimaciones", "suggestedOnly: true"],
  },
  {
    type:                  "APERTURA_SUCURSAL",
    title:                 "Apertura de Nueva Sucursal",
    description:           "Decisión de expansión física con implicaciones de capital y operaciones",
    primaryPerspectives:   ["FINANCE", "OPERATIONS", "STRATEGY"],
    secondaryPerspectives: ["COMMERCIAL", "COMPLIANCE"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Timing de inversión vs condiciones de mercado"],
    keyConsensusPoints:    ["Análisis de viabilidad financiera primero", "Estudio de ubicación"],
    topRecommendationTitles: [
      "Realizar estudio de factibilidad",
      "Definir estructura de financiamiento",
      "Validar cumplimiento regulatorio local",
    ],
    limitations:           ["Permisos y regulaciones pueden variar", "suggestedOnly: true"],
  },
  {
    type:                  "PERDIDA_CLIENTE_ESTRATEGICO",
    title:                 "Pérdida de Cliente Estratégico",
    description:           "Desvinculación de un cliente que representa más del 15% de ingresos",
    primaryPerspectives:   ["COMMERCIAL", "FINANCE", "EXECUTIVE"],
    secondaryPerspectives: ["STRATEGY", "COLLECTIONS"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Estrategia de retención vs diversificación inmediata"],
    keyConsensusPoints:    ["Activar plan de retención urgente", "Identificar clientes sustitutos"],
    topRecommendationTitles: [
      "Reunión ejecutiva de retención en 48h",
      "Activar pipeline de nuevos clientes objetivo",
      "Revisar condiciones contractuales",
    ],
    limitations:           ["Resultado de negociación incierto", "suggestedOnly: true"],
  },
  {
    type:                  "INCREMENTO_COSTOS_OPERATIVOS",
    title:                 "Incremento Sostenido de Costos Operativos",
    description:           "Aumento de costos fijos por encima del 20% en comparación con período anterior",
    primaryPerspectives:   ["FINANCE", "OPERATIONS", "EXECUTIVE"],
    secondaryPerspectives: ["COMPLIANCE", "STRATEGY"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Alcance de las medidas de optimización"],
    keyConsensusPoints:    ["Mapear causas raíz", "Plan de reducción en 60 días"],
    topRecommendationTitles: [
      "Auditoría de estructura de costos",
      "Renegociar contratos con proveedores clave",
      "Optimizar procesos de mayor impacto",
    ],
    limitations:           ["Ahorros proyectados pueden no materializarse al 100%", "suggestedOnly: true"],
  },
  {
    type:                  "RIESGO_REGULATORIO",
    title:                 "Riesgo Regulatorio Emergente",
    description:           "Nueva normativa o cambio regulatorio con impacto sobre operaciones o finanzas",
    primaryPerspectives:   ["COMPLIANCE", "RISK", "EXECUTIVE"],
    secondaryPerspectives: ["FINANCE", "OPERATIONS"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Velocidad de adaptación vs costo de cumplimiento"],
    keyConsensusPoints:    ["Evaluación legal inmediata", "Plan de adecuación"],
    topRecommendationTitles: [
      "Contratar asesoría legal especializada",
      "Mapear impacto operativo y financiero",
      "Definir plan de adecuación con plazos",
    ],
    limitations:           ["Interpretación regulatoria puede variar", "suggestedOnly: true"],
  },
  {
    type:                  "CONFLICTO_OBJETIVOS_ESTRATEGICOS",
    title:                 "Conflicto de Objetivos Estratégicos",
    description:           "Dos o más objetivos estratégicos activos con recursos o prioridades en tensión",
    primaryPerspectives:   ["STRATEGY", "EXECUTIVE", "FINANCE"],
    secondaryPerspectives: ["OPERATIONS", "COMMERCIAL"],
    expectedOutcome:       "ESCALATION_REQUIRED",
    keyDisagreements:      ["Priorización de recursos entre objetivos rivales"],
    keyConsensusPoints:    ["Necesidad de decisión ejecutiva directiva"],
    topRecommendationTitles: [
      "Sesión ejecutiva de repriorización",
      "Definir criterios de asignación de recursos",
      "Revisar roadmap estratégico",
    ],
    limitations:           ["Requiere decisión directiva — no automatizable", "suggestedOnly: true"],
  },
  {
    type:                  "OPORTUNIDAD_MERCADO_IGNORADA",
    title:                 "Oportunidad de Mercado Sin Atender",
    description:           "Señales claras de demanda insatisfecha o gap competitivo sin acción actual",
    primaryPerspectives:   ["COMMERCIAL", "MARKETING", "STRATEGY"],
    secondaryPerspectives: ["FINANCE", "OPERATIONS"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Velocidad de captura vs capacidad operativa"],
    keyConsensusPoints:    ["Validar oportunidad con datos", "Definir recursos mínimos para piloto"],
    topRecommendationTitles: [
      "Análisis de oportunidad en 2 semanas",
      "Definir propuesta de valor diferenciada",
      "Evaluar capacidad de entrega",
    ],
    limitations:           ["Ventana de oportunidad puede cerrarse", "suggestedOnly: true"],
  },
  {
    type:                  "DETERIORO_PORTAFOLIO_COBRANZA",
    title:                 "Deterioro del Portafolio de Cobranza",
    description:           "Aumento de cartera vencida mayor a 60 días con riesgo de incobrabilidad",
    primaryPerspectives:   ["COLLECTIONS", "FINANCE", "RISK"],
    secondaryPerspectives: ["COMMERCIAL", "COMPLIANCE"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Estrategia de castigo vs renegociación de deuda"],
    keyConsensusPoints:    ["Segmentar cartera por recuperabilidad", "Activar cobranza jurídica selectiva"],
    topRecommendationTitles: [
      "Segmentar cartera por antigüedad y perfil",
      "Activar cobranza preventiva en cuentas críticas",
      "Evaluar provisión contable requerida",
    ],
    limitations:           ["Recuperabilidad depende del perfil del deudor", "suggestedOnly: true"],
  },
  {
    type:                  "CAIDA_RENTABILIDAD",
    title:                 "Caída de Rentabilidad",
    description:           "Margen neto por debajo del objetivo por más de dos períodos consecutivos",
    primaryPerspectives:   ["FINANCE", "COMMERCIAL", "EXECUTIVE"],
    secondaryPerspectives: ["OPERATIONS", "STRATEGY"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Reducción de costos vs inversión en crecimiento"],
    keyConsensusPoints:    ["Análisis de mix de ingresos y márgenes por producto"],
    topRecommendationTitles: [
      "Análisis de rentabilidad por producto/servicio",
      "Revisar política de precios",
      "Identificar palancas de mejora de margen",
    ],
    limitations:           ["Múltiples factores externos pueden influir", "suggestedOnly: true"],
  },
  {
    type:                  "LANZAMIENTO_PRODUCTO",
    title:                 "Lanzamiento de Nuevo Producto o Servicio",
    description:           "Decisión de introducir un nuevo producto al mercado con inversión asociada",
    primaryPerspectives:   ["COMMERCIAL", "MARKETING", "FINANCE"],
    secondaryPerspectives: ["OPERATIONS", "COMPLIANCE"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Timing de lanzamiento vs preparación interna"],
    keyConsensusPoints:    ["Plan de go-to-market", "Presupuesto de lanzamiento acotado"],
    topRecommendationTitles: [
      "Validar fit de mercado con cliente piloto",
      "Definir presupuesto y ROI esperado",
      "Alinear operaciones para escalar",
    ],
    limitations:           ["Respuesta del mercado es incierta", "suggestedOnly: true"],
  },
  {
    type:                  "CRISIS_REPUTACIONAL",
    title:                 "Crisis Reputacional",
    description:           "Evento que amenaza la imagen o reputación de la empresa en el mercado",
    primaryPerspectives:   ["EXECUTIVE", "COMPLIANCE", "COMMERCIAL"],
    secondaryPerspectives: ["MARKETING", "RISK"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Comunicación pública vs gestión interna"],
    keyConsensusPoints:    ["Respuesta rápida y transparente", "Comité de crisis activado"],
    topRecommendationTitles: [
      "Activar protocolo de gestión de crisis",
      "Designar vocero oficial",
      "Documentar hechos y medidas correctivas",
    ],
    limitations:           ["Reputación difícil de cuantificar en corto plazo", "suggestedOnly: true"],
  },
  {
    type:                  "TRANSFORMACION_DIGITAL",
    title:                 "Transformación Digital Operativa",
    description:           "Proyecto de digitalización que afecta múltiples áreas y requiere inversión significativa",
    primaryPerspectives:   ["OPERATIONS", "STRATEGY", "FINANCE"],
    secondaryPerspectives: ["COMPLIANCE", "EXECUTIVE"],
    expectedOutcome:       "PARTIAL_CONSENSUS",
    keyDisagreements:      ["Alcance de la transformación vs recursos disponibles"],
    keyConsensusPoints:    ["Priorizar procesos de mayor impacto", "Fases iterativas de implementación"],
    topRecommendationTitles: [
      "Mapear procesos críticos a digitalizar",
      "Evaluar proveedores tecnológicos",
      "Diseñar plan de cambio organizacional",
    ],
    limitations:           ["ROI de transformación digital es de largo plazo", "suggestedOnly: true"],
  },
  {
    type:                  "CONFLICTO_PRIORIDADES_PRESUPUESTALES",
    title:                 "Conflicto de Prioridades Presupuestales",
    description:           "Múltiples áreas compitiendo por recursos limitados del presupuesto",
    primaryPerspectives:   ["FINANCE", "EXECUTIVE", "STRATEGY"],
    secondaryPerspectives: ["COMMERCIAL", "OPERATIONS", "MARKETING"],
    expectedOutcome:       "ESCALATION_REQUIRED",
    keyDisagreements:      ["Criterios de asignación presupuestal entre áreas"],
    keyConsensusPoints:    ["Marco de priorización basado en impacto", "Revisión trimestral de asignación"],
    topRecommendationTitles: [
      "Establecer matriz de priorización presupuestal",
      "Sesión ejecutiva de alineamiento de recursos",
      "Definir reserva estratégica",
    ],
    limitations:           ["Decisión final requiere autoridad ejecutiva", "suggestedOnly: true"],
  },
  {
    type:                  "DETERIORO_CLIMA_ORGANIZACIONAL",
    title:                 "Deterioro del Clima Organizacional",
    description:           "Señales de desmotivación, alta rotación o conflictos internos que afectan productividad",
    primaryPerspectives:   ["EXECUTIVE", "OPERATIONS", "STRATEGY"],
    secondaryPerspectives: ["COMPLIANCE", "FINANCE"],
    expectedOutcome:       "CONSENSUS",
    keyDisagreements:      ["Medidas correctivas inmediatas vs cambios estructurales"],
    keyConsensusPoints:    ["Diagnóstico organizacional", "Plan de mejora de clima"],
    topRecommendationTitles: [
      "Aplicar diagnóstico de clima organizacional",
      "Revisar estructura de incentivos",
      "Sesiones de retroalimentación con equipos clave",
    ],
    limitations:           ["Cambio de clima requiere tiempo y consistencia", "suggestedOnly: true"],
  },
];
