/**
 * lib/agent-memory/context-edges.ts
 *
 * Agentik Agent Runtime — Context Edge Builders
 *
 * Typed builders for RuntimeMemoryEdge relationships.
 * Every edge must express a clear semantic relationship.
 * No "generic" edges — every relation type has a defined meaning.
 *
 * Sprint: AGENTIK-AGENT-CONTEXT-MEMORY-GRAPH-01
 */

import { memEdgeId } from "./runtime-memory-store";
import type { RuntimeMemoryEdge, EdgeRelationType } from "./runtime-memory-types";

// ── Generic edge builder ──────────────────────────────────────────────────────

export function buildEdge(
  sourceId:     string,
  targetId:     string,
  relationType: EdgeRelationType,
  metadata:     Record<string, unknown> = {},
): RuntimeMemoryEdge {
  return {
    id:           memEdgeId(),
    sourceId,
    targetId,
    relationType,
    createdAt:    new Date().toISOString(),
    metadata,
  };
}

// ── Semantic edge builders ─────────────────────────────────────────────────────

/**
 * "A was caused by B" — B triggered A.
 * Example: action_failed caused_by action_approved (where approval led to failed exec)
 */
export function causedBy(
  effectNodeId: string,
  causeNodeId:  string,
  meta?: Record<string, unknown>,
): RuntimeMemoryEdge {
  return buildEdge(effectNodeId, causeNodeId, "caused_by", meta);
}

/**
 * "A depends on B" — A cannot execute until B completes.
 * Example: Luca campaign pause depends_on David inventory approval.
 */
export function dependsOn(
  dependentId:  string,
  dependencyId: string,
  meta?: Record<string, unknown>,
): RuntimeMemoryEdge {
  return buildEdge(dependentId, dependencyId, "depends_on", meta);
}

/**
 * "Action node was approved by decision node."
 */
export function approvedBy(
  actionNodeId:   string,
  decisionNodeId: string,
  approvedByUser: string,
): RuntimeMemoryEdge {
  return buildEdge(actionNodeId, decisionNodeId, "approved_by", { approvedByUser });
}

/**
 * "Action node was rejected by decision node."
 */
export function rejectedBy(
  actionNodeId:   string,
  decisionNodeId: string,
  rejectedByUser: string,
  reason?:        string,
): RuntimeMemoryEdge {
  return buildEdge(actionNodeId, decisionNodeId, "rejected_by", { rejectedByUser, reason: reason ?? null });
}

/**
 * "Node was generated by agent."
 * Links an observation or event node to the agent that produced it.
 */
export function generatedBy(
  nodeId:  string,
  agentId: string,
): RuntimeMemoryEdge {
  return buildEdge(nodeId, agentId, "generated_by", { agentId });
}

/**
 * "Node affects module."
 * Tracks which modules are impacted by an action.
 */
export function affectsModule(
  nodeId:   string,
  moduleId: string,
): RuntimeMemoryEdge {
  return buildEdge(nodeId, moduleId, "affects_module", { moduleId });
}

/**
 * "B follows A" — A happened before B in the same operational chain.
 */
export function follows(
  nextNodeId: string,
  prevNodeId: string,
  meta?: Record<string, unknown>,
): RuntimeMemoryEdge {
  return buildEdge(nextNodeId, prevNodeId, "follows", meta);
}

/**
 * "A was escalated from B" — B raised the issue, A is the escalated action.
 */
export function escalatedFrom(
  escalatedNodeId: string,
  sourceNodeId:    string,
): RuntimeMemoryEdge {
  return buildEdge(escalatedNodeId, sourceNodeId, "escalated_from", {});
}

/**
 * "A was delegated to B" — A delegated its execution responsibility to B.
 */
export function delegatedTo(
  delegatingNodeId: string,
  delegateNodeId:   string,
  delegateAgentId:  string,
): RuntimeMemoryEdge {
  return buildEdge(delegatingNodeId, delegateNodeId, "delegated_to", { delegateAgentId });
}

/**
 * "A blocks B" — A must resolve before B can proceed.
 * Used when a delegation blocks a parent action.
 */
export function blocks(
  blockingNodeId: string,
  blockedNodeId:  string,
  meta?: Record<string, unknown>,
): RuntimeMemoryEdge {
  return buildEdge(blockingNodeId, blockedNodeId, "blocks", meta);
}

/**
 * "A resolves B" — A's completion unblocks B.
 * Used when a delegation completion unlocks a parent action.
 */
export function resolves(
  resolvingNodeId: string,
  blockedNodeId:   string,
  meta?: Record<string, unknown>,
): RuntimeMemoryEdge {
  return buildEdge(resolvingNodeId, blockedNodeId, "resolves", meta);
}

// ── Edge chain builder ────────────────────────────────────────────────────────
//
// Builds a sequential chain of "follows" edges from an ordered list of node IDs.

export function buildFollowsChain(nodeIds: string[]): RuntimeMemoryEdge[] {
  const edges: RuntimeMemoryEdge[] = [];
  for (let i = 1; i < nodeIds.length; i++) {
    edges.push(follows(nodeIds[i]!, nodeIds[i - 1]!));
  }
  return edges;
}

// ── Edge metadata helpers ─────────────────────────────────────────────────────

export function edgeSummary(edge: RuntimeMemoryEdge): string {
  const rel = edge.relationType.replace(/_/g, " ");
  return `${edge.sourceId.slice(0, 12)}… ${rel} ${edge.targetId.slice(0, 12)}…`;
}
