/**
 * lib/agent-memory/runtime-memory-types.ts
 *
 * Agentik Agent Runtime — Operational Memory Types
 *
 * These are the core types for the memory graph layer.
 * All types are fully serializable (ISO strings, plain objects).
 * No Date objects, no class instances, no circular refs.
 *
 * V1: In-memory process-scoped store.
 * V2: Prisma AgentMemoryNode + AgentMemoryEdge models.
 * V3: Graph DB (Neo4j/Dgraph) or vector store.
 *
 * Sprint: AGENTIK-AGENT-CONTEXT-MEMORY-GRAPH-01
 */

import type { AgentRuntimeId, AgentDomain } from "@/lib/agent-runtime/agent-types";

// ── Node types ────────────────────────────────────────────────────────────────

export type RuntimeMemoryNodeType =
  | "action_proposed"     // Agent proposed an action
  | "action_approved"     // User approved an action
  | "action_rejected"     // User rejected an action
  | "action_executing"    // Execution started
  | "action_executed"     // Execution completed
  | "action_failed"       // Execution failed
  | "agent_observation"   // Agent recorded an operational observation
  | "module_event"        // A module-level operational event
  | "decision_point"      // A human decision was made
  | "context_snapshot"    // A context snapshot was captured
  | "runtime_event";      // A generic runtime event

// ── Edge relation types ───────────────────────────────────────────────────────

export type EdgeRelationType =
  | "caused_by"       // this node was caused by another
  | "depends_on"      // this node depends on another (execution dependency)
  | "approved_by"     // this action was approved by a decision node
  | "rejected_by"     // this action was rejected by a decision node
  | "generated_by"    // this node was generated by an agent
  | "affects_module"  // this node affects a module
  | "escalated_from"  // escalated from another agent/module
  | "delegated_to"    // delegated execution to another agent
  | "follows"         // sequential temporal relationship
  | "contradicts"     // this decision overrides/contradicts another
  | "references"      // informational reference (no causality)
  | "blocks"          // this node/delegation blocks another from proceeding
  | "resolves";       // this node/delegation resolves a blocked dependency

// ── Severity scale ────────────────────────────────────────────────────────────

export type MemoryNodeSeverity = "critical" | "high" | "medium" | "low" | "info";

// ── Core node ─────────────────────────────────────────────────────────────────

export interface RuntimeMemoryNode {
  /** Unique node ID — "mn_{timestamp}_{seq}" */
  id:             string;
  /** ISO timestamp */
  timestamp:      string;
  /** Organization scope */
  orgId:          string;
  /** Agent that produced or is associated with this node */
  agentId:        AgentRuntimeId | string;
  /** Module key — "comercial.maletas" | "finanzas.conciliacion" | etc. */
  moduleId:       string;
  /** Linked ActionTask or AgentAction ID (null for observation nodes) */
  actionId:       string | null;
  /** Type of operational event */
  nodeType:       RuntimeMemoryNodeType;
  /** Human-readable summary — operational language, enterprise-terse */
  summary:        string;
  /** Structured payload — all fields serializable */
  metadata:       Record<string, unknown>;
  /** IDs of RuntimeMemoryEdges connected to this node */
  relatedEdges:   string[];
  /** Operational severity */
  severity:       MemoryNodeSeverity;
  /** Current lifecycle state of the related action (if applicable) */
  lifecycleState: string;
  /** Domain for grouping */
  domain:         AgentDomain | string;
  /** Actor (user ID or agent ID) who triggered or observed this event */
  actorId:        string | null;
}

// ── Edge ─────────────────────────────────────────────────────────────────────

export interface RuntimeMemoryEdge {
  /** Unique edge ID — "me_{timestamp}_{seq}" */
  id:           string;
  /** Source node ID */
  sourceId:     string;
  /** Target node ID */
  targetId:     string;
  /** Semantic relation type */
  relationType: EdgeRelationType;
  /** ISO timestamp */
  createdAt:    string;
  /** Optional context about this relationship */
  metadata:     Record<string, unknown>;
}

// ── Agent observation ─────────────────────────────────────────────────────────

export interface AgentObservation {
  id:          string;
  timestamp:   string;
  orgId:       string;
  agentId:     AgentRuntimeId | string;
  moduleId:    string;
  /** Operational observation — no conversational filler */
  observation: string;
  /** What triggered this observation */
  trigger:     string | null;
  /** Linked memory node ID (if observation was persisted as a node) */
  nodeId:      string | null;
  severity:    MemoryNodeSeverity;
  metadata:    Record<string, unknown>;
}

// ── ActionContextNode — rich context built from ActionEnvelope ────────────────

export interface ActionContextNode {
  /** The memory node representing this action */
  node:          RuntimeMemoryNode;
  /** Edges connecting this action to related entities */
  edges:         RuntimeMemoryEdge[];
  /** Related observations from the proposing agent */
  observations:  AgentObservation[];
}

// ── Memory query result ───────────────────────────────────────────────────────

export interface MemoryQueryResult {
  nodes:      RuntimeMemoryNode[];
  edges:      RuntimeMemoryEdge[];
  total:      number;
  queryMeta:  Record<string, unknown>;
}

// ── Memory diagnostics (for dev panel) ───────────────────────────────────────

export interface MemoryDiagnostics {
  totalNodes:          number;
  totalEdges:          number;
  totalObservations:   number;
  nodesByType:         Record<string, number>;
  nodesByAgent:        Record<string, number>;
  topModulesAffected:  Array<{ moduleId: string; count: number }>;
  recentObservations:  AgentObservation[];
  orphanActionCount:   number;
  longestChainLength:  number;
  storeType:           string;
}
